/* @generated by modelblaster/pipeline/ingest_xpurt_schedule.py — do not edit. */
#include <stddef.h>
#include "ku040_dronet_nhwc_dev.h"

static const int sched_0_harts[] = { 1 };
static const int sched_0_fanout[] = { 1 };
static const int sched_1_harts[] = { 1 };
static const int sched_1_deps[] = { 0 };
static const int sched_1_fanout[] = { 2, 3 };
static const int sched_2_harts[] = { 1 };
static const int sched_2_deps[] = { 1 };
static const int sched_2_fanout[] = { 4 };
static const int sched_3_harts[] = { 1 };
static const int sched_3_deps[] = { 1 };
static const int sched_3_fanout[] = { 8 };
static const int sched_4_harts[] = { 0 };
static const int sched_4_deps[] = { 2 };
static const int sched_4_fanout[] = { 5 };
static const int sched_5_harts[] = { 1 };
static const int sched_5_deps[] = { 4 };
static const int sched_5_fanout[] = { 6 };
static const int sched_6_harts[] = { 1 };
static const int sched_6_deps[] = { 5 };
static const int sched_6_fanout[] = { 7 };
static const int sched_7_harts[] = { 1 };
static const int sched_7_deps[] = { 6 };
static const int sched_7_fanout[] = { 8 };
static const int sched_8_harts[] = { 0 };
static const int sched_8_deps[] = { 3, 7 };
static const int sched_8_fanout[] = { 9, 10 };
static const int sched_9_harts[] = { 1 };
static const int sched_9_deps[] = { 8 };
static const int sched_9_fanout[] = { 11 };
static const int sched_10_harts[] = { 1 };
static const int sched_10_deps[] = { 8 };
static const int sched_10_fanout[] = { 15 };
static const int sched_11_harts[] = { 0 };
static const int sched_11_deps[] = { 9 };
static const int sched_11_fanout[] = { 12 };
static const int sched_12_harts[] = { 1 };
static const int sched_12_deps[] = { 11 };
static const int sched_12_fanout[] = { 13 };
static const int sched_13_harts[] = { 1 };
static const int sched_13_deps[] = { 12 };
static const int sched_13_fanout[] = { 14 };
static const int sched_14_harts[] = { 1 };
static const int sched_14_deps[] = { 13 };
static const int sched_14_fanout[] = { 15 };
static const int sched_15_harts[] = { 0 };
static const int sched_15_deps[] = { 10, 14 };
static const int sched_15_fanout[] = { 16, 17 };
static const int sched_16_harts[] = { 1 };
static const int sched_16_deps[] = { 15 };
static const int sched_16_fanout[] = { 18 };
static const int sched_17_harts[] = { 1 };
static const int sched_17_deps[] = { 15 };
static const int sched_17_fanout[] = { 22 };
static const int sched_18_harts[] = { 0 };
static const int sched_18_deps[] = { 16 };
static const int sched_18_fanout[] = { 19 };
static const int sched_19_harts[] = { 1 };
static const int sched_19_deps[] = { 18 };
static const int sched_19_fanout[] = { 20 };
static const int sched_20_harts[] = { 1 };
static const int sched_20_deps[] = { 19 };
static const int sched_20_fanout[] = { 21 };
static const int sched_21_harts[] = { 1 };
static const int sched_21_deps[] = { 20 };
static const int sched_21_fanout[] = { 22 };
static const int sched_22_harts[] = { 0 };
static const int sched_22_deps[] = { 17, 21 };
static const int sched_22_fanout[] = { 23 };
static const int sched_23_harts[] = { 1 };
static const int sched_23_deps[] = { 22 };
static const int sched_23_fanout[] = { 24 };
static const int sched_24_harts[] = { 0 };
static const int sched_24_deps[] = { 23 };
static const int sched_24_fanout[] = { 25, 26 };
static const int sched_25_harts[] = { 0 };
static const int sched_25_deps[] = { 24 };
static const int sched_26_harts[] = { 0 };
static const int sched_26_deps[] = { 24 };
static const int sched_26_fanout[] = { 27 };
static const int sched_27_harts[] = { 0 };
static const int sched_27_deps[] = { 26 };

const xpurt_sched_entry_t KU040_DRONET_NHWC_DEV_TABLE[KU040_DRONET_NHWC_DEV_N_ENTRIES] = {
    { .entry_id = 0, .network = "dronet", .instance = 0, .dispatch_id = 0, .job_name = "dronet", .op = "nchw_to_nhwc_s8", .name = "relayout_in.x", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_0_harts, .start_time_ms = 0.0f, .duration_ms = 0.005f, .n_deps = 0, .deps = NULL, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_0_fanout },
    { .entry_id = 1, .network = "dronet", .instance = 0, .dispatch_id = 1, .job_name = "dronet", .op = "conv2d_pool_s8", .name = "conv_modules.0", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_1_harts, .start_time_ms = 0.005f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_1_deps, .time_dep_entry_id = -1, .n_fanout = 2, .fanout = sched_1_fanout },
    { .entry_id = 2, .network = "dronet", .instance = 0, .dispatch_id = 2, .job_name = "dronet", .op = "nhwc_to_nchw_s8", .name = "relayout_out.maxpool1", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_2_harts, .start_time_ms = 0.01f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_2_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_2_fanout },
    { .entry_id = 3, .network = "dronet", .instance = 0, .dispatch_id = 7, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.3", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_3_harts, .start_time_ms = 0.015f, .duration_ms = 0.035f, .n_deps = 1, .deps = sched_3_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_3_fanout },
    { .entry_id = 4, .network = "dronet", .instance = 0, .dispatch_id = 3, .job_name = "dronet", .op = "batchnorm2d_s8", .name = "bn_modules.0", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_4_harts, .start_time_ms = 0.05f, .duration_ms = 0.004f, .n_deps = 1, .deps = sched_4_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_4_fanout },
    { .entry_id = 5, .network = "dronet", .instance = 0, .dispatch_id = 4, .job_name = "dronet", .op = "nchw_to_nhwc_s8", .name = "relayout_in.relu_modules_0", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_5_harts, .start_time_ms = 0.054f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_5_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_5_fanout },
    { .entry_id = 6, .network = "dronet", .instance = 0, .dispatch_id = 5, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.1", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_6_harts, .start_time_ms = 0.059f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_6_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_6_fanout },
    { .entry_id = 7, .network = "dronet", .instance = 0, .dispatch_id = 6, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.2", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_7_harts, .start_time_ms = 0.079f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_7_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_7_fanout },
    { .entry_id = 8, .network = "dronet", .instance = 0, .dispatch_id = 8, .job_name = "dronet", .op = "add_s8", .name = "add", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_8_harts, .start_time_ms = 0.099f, .duration_ms = 0.0025f, .n_deps = 2, .deps = sched_8_deps, .time_dep_entry_id = -1, .n_fanout = 2, .fanout = sched_8_fanout },
    { .entry_id = 9, .network = "dronet", .instance = 0, .dispatch_id = 9, .job_name = "dronet", .op = "nhwc_to_nchw_s8", .name = "relayout_out.add", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_9_harts, .start_time_ms = 0.1015f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_9_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_9_fanout },
    { .entry_id = 10, .network = "dronet", .instance = 0, .dispatch_id = 14, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.6", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_10_harts, .start_time_ms = 0.1065f, .duration_ms = 0.035f, .n_deps = 1, .deps = sched_10_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_10_fanout },
    { .entry_id = 11, .network = "dronet", .instance = 0, .dispatch_id = 10, .job_name = "dronet", .op = "batchnorm2d_s8", .name = "bn_modules.2", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_11_harts, .start_time_ms = 0.1415f, .duration_ms = 0.004f, .n_deps = 1, .deps = sched_11_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_11_fanout },
    { .entry_id = 12, .network = "dronet", .instance = 0, .dispatch_id = 11, .job_name = "dronet", .op = "nchw_to_nhwc_s8", .name = "relayout_in.relu_modules_2", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_12_harts, .start_time_ms = 0.1455f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_12_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_12_fanout },
    { .entry_id = 13, .network = "dronet", .instance = 0, .dispatch_id = 12, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.4", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_13_harts, .start_time_ms = 0.1505f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_13_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_13_fanout },
    { .entry_id = 14, .network = "dronet", .instance = 0, .dispatch_id = 13, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.5", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_14_harts, .start_time_ms = 0.1705f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_14_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_14_fanout },
    { .entry_id = 15, .network = "dronet", .instance = 0, .dispatch_id = 15, .job_name = "dronet", .op = "add_s8", .name = "add_1", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_15_harts, .start_time_ms = 0.1905f, .duration_ms = 0.0025f, .n_deps = 2, .deps = sched_15_deps, .time_dep_entry_id = -1, .n_fanout = 2, .fanout = sched_15_fanout },
    { .entry_id = 16, .network = "dronet", .instance = 0, .dispatch_id = 16, .job_name = "dronet", .op = "nhwc_to_nchw_s8", .name = "relayout_out.add_1", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_16_harts, .start_time_ms = 0.193f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_16_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_16_fanout },
    { .entry_id = 17, .network = "dronet", .instance = 0, .dispatch_id = 21, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.9", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_17_harts, .start_time_ms = 0.198f, .duration_ms = 0.035f, .n_deps = 1, .deps = sched_17_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_17_fanout },
    { .entry_id = 18, .network = "dronet", .instance = 0, .dispatch_id = 17, .job_name = "dronet", .op = "batchnorm2d_s8", .name = "bn_modules.4", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_18_harts, .start_time_ms = 0.233f, .duration_ms = 0.004f, .n_deps = 1, .deps = sched_18_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_18_fanout },
    { .entry_id = 19, .network = "dronet", .instance = 0, .dispatch_id = 18, .job_name = "dronet", .op = "nchw_to_nhwc_s8", .name = "relayout_in.relu_modules_4", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_19_harts, .start_time_ms = 0.237f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_19_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_19_fanout },
    { .entry_id = 20, .network = "dronet", .instance = 0, .dispatch_id = 19, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.7", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_20_harts, .start_time_ms = 0.242f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_20_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_20_fanout },
    { .entry_id = 21, .network = "dronet", .instance = 0, .dispatch_id = 20, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.8", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_21_harts, .start_time_ms = 0.262f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_21_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_21_fanout },
    { .entry_id = 22, .network = "dronet", .instance = 0, .dispatch_id = 22, .job_name = "dronet", .op = "add_s8", .name = "add_2", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_22_harts, .start_time_ms = 0.282f, .duration_ms = 0.0025f, .n_deps = 2, .deps = sched_22_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_22_fanout },
    { .entry_id = 23, .network = "dronet", .instance = 0, .dispatch_id = 23, .job_name = "dronet", .op = "nhwc_to_nchw_s8", .name = "relayout_out.add_2", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_23_harts, .start_time_ms = 0.2845f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_23_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_23_fanout },
    { .entry_id = 24, .network = "dronet", .instance = 0, .dispatch_id = 24, .job_name = "dronet", .op = "relu_s8", .name = "relu_modules.6", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_24_harts, .start_time_ms = 0.2895f, .duration_ms = 0.002f, .n_deps = 1, .deps = sched_24_deps, .time_dep_entry_id = -1, .n_fanout = 2, .fanout = sched_24_fanout },
    { .entry_id = 25, .network = "dronet", .instance = 0, .dispatch_id = 25, .job_name = "dronet", .op = "linear_s8", .name = "linear1", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_25_harts, .start_time_ms = 0.2915f, .duration_ms = 0.008f, .n_deps = 1, .deps = sched_25_deps, .time_dep_entry_id = -1, .n_fanout = 0, .fanout = NULL },
    { .entry_id = 26, .network = "dronet", .instance = 0, .dispatch_id = 26, .job_name = "dronet", .op = "linear_s8", .name = "linear2", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_26_harts, .start_time_ms = 0.2995f, .duration_ms = 0.008f, .n_deps = 1, .deps = sched_26_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_26_fanout },
    { .entry_id = 27, .network = "dronet", .instance = 0, .dispatch_id = 27, .job_name = "dronet", .op = "sigmoid_s8", .name = "sigmoid1", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_27_harts, .start_time_ms = 0.3075f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_27_deps, .time_dep_entry_id = -1, .n_fanout = 0, .fanout = NULL },
};
