/* source: curated */
/* algorithm: ime_vmadot_4x4x8 */
/* accuracy_class: bit_exact */
/* origin: generated by pipeline/generate_kernels.py via Codex (gpt-5.6-sol),
 *   first attempt, from the ime_vmadot_4x4x8 seed in reference_kernels.py.
 *
 * THE FOUR FACTS THIS KERNEL RESTS ON WERE MEASURED, NOT ASSUMED:
 *   1. micro-tile 4x4x8, hardware-forced (vl*SEW indexes the MAC table, not
 *      VLEN: vl=32, e8 -> 4x4x8). vsetvli vl=32,e8,m1 must be live AT the
 *      instruction or it SIGILLs.
 *   2. vmadot ACCUMULATES: vd += A . B^T. Confirmed by issuing identical
 *      operands twice and watching every result double, which is what makes
 *      K>8 a loop rather than impossible.
 *   3. the 16 int32 results are ROW-MAJOR across the pair (vd, vd+1):
 *      element e is C[e/4][e%4]. See scripts/k1_ime_accumulator_probe.c.
 *   4. CLUSTER 0 ONLY. Harts 4-7 exit 132 (SIGILL) on this instruction, so a
 *      schedule that places an ime dispatch on CPU_E cannot run.
 *
 * vs2 is indexed [j][k], so the unit natively computes the transpose_b=1
 * case with no repacking. transpose_b=0 needs the 4x8 B tile transposed into
 * scratch first -- 32 bytes against 128 MACs.
 *
 * The requantize tail is scalar for the same reason as the RVV kernel: the
 * oracle rounds half-away-from-zero (roundf) and RVV float conversion rounds
 * to nearest-even, so a vectorized tail loses max_abs_err=0.
 */


void kernel_matmul_s8(const int8_t *a, const int8_t *b, int8_t *output, int M, int K, int N, float scale_a, float scale_b, float scale_out, int transpose_b, float scale_div, int activation_min, int activation_max)
{
    int k_slabs = K > 0 ? (K + 7) / 8 : 1;
    int8_t a_tiles[k_slabs * 32];
    int8_t b_tiles[k_slabs * 32];
    int32_t out16[16];
    float total = (scale_a * scale_b) / (scale_out * scale_div);

    for (int m0 = 0; m0 < M; m0 += 4) {
        for (int n0 = 0; n0 < N; n0 += 4) {
            for (int slab = 0; slab < k_slabs; slab++) {
                for (int i = 0; i < 4; i++) {
                    for (int lane = 0; lane < 8; lane++) {
                        int k = slab * 8 + lane;
                        int index = slab * 32 + i * 8 + lane;

                        if (m0 + i < M && k < K)
                            a_tiles[index] = a[(m0 + i) * K + k];
                        else
                            a_tiles[index] = 0;
                    }
                }

                for (int j = 0; j < 4; j++) {
                    for (int lane = 0; lane < 8; lane++) {
                        int k = slab * 8 + lane;
                        int index = slab * 32 + j * 8 + lane;

                        if (n0 + j < N && k < K) {
                            if (transpose_b)
                                b_tiles[index] = b[(n0 + j) * K + k];
                            else
                                b_tiles[index] = b[k * N + n0 + j];
                        } else {
                            b_tiles[index] = 0;
                        }
                    }
                }
            }

            {
                const int8_t *a_ptr = a_tiles;
                const int8_t *b_ptr = b_tiles;
                int slabs_left = k_slabs;
                size_t n32 = 32;
                size_t n8 = 8;

                __asm__ volatile(
                    "vsetvli t0, %[n32], e8, m1, ta, ma\n\t"
                    "vmv.v.i v8, 0\n\t"
                    "vmv.v.i v9, 0\n\t"
                    "1:\n\t"
                    "vsetvli t0, %[n32], e8, m1, ta, ma\n\t"
                    "vle8.v v0, (%[pa])\n\t"
                    "vle8.v v4, (%[pb])\n\t"
                    "vsetvli t0, %[n32], e8, m1, ta, ma\n\t"
                    ".insn r 0x2b, 3, 0x71, x8, x0, x4\n\t"
                    "addi %[pa], %[pa], 32\n\t"
                    "addi %[pb], %[pb], 32\n\t"
                    "addi %[ks], %[ks], -1\n\t"
                    "bnez %[ks], 1b\n\t"
                    "vsetvli t0, %[n8], e32, m1, ta, ma\n\t"
                    "vse32.v v8, (%[o0])\n\t"
                    "vse32.v v9, (%[o1])\n\t"
                    : [pa] "+r"(a_ptr), [pb] "+r"(b_ptr),
                      [ks] "+r"(slabs_left)
                    : [o0] "r"(out16), [o1] "r"(out16 + 8),
                      [n32] "r"(n32), [n8] "r"(n8)
                    : "t0", "memory", "v0", "v4", "v8", "v9");
            }

            for (int i = 0; i < 4 && m0 + i < M; i++) {
                for (int j = 0; j < 4 && n0 + j < N; j++) {
                    int32_t value =
                        (int32_t)roundf((float)out16[i * 4 + j] * total);

                    if (value < activation_min)
                        value = activation_min;
                    if (value > activation_max)
                        value = activation_max;

                    output[(m0 + i) * N + n0 + j] = (int8_t)value;
                }
            }
        }
    }
}
