"""Emit a multi-network main.c that walks an XPU-RT dispatch table.

Companion to ``ingest_xpurt_schedule`` (which produces the C dispatch
table). Together they close the round trip:

    XPU-RT schedule.json
        -> ingest_xpurt_schedule  -> <name>_dispatch_table.{h,c}
        -> generate_xpurt_main    -> <name>_main.c
        -> west build (harness_xpurt)
        -> spike

The harness can link multiple HW backends per model (e.g. scalar + rvv);
the walker dispatches each entry to whichever backend's per-model table
matches the entry's ``core_kind``. Symbol disambiguation is handled at
compile time by ``backend_rename.py`` — each model's externally-visible
symbols (kernels, dispatch table, profile API) get suffixed with
``_<bs>`` per backend.

The generated main:

    1. Creates one modelblaster_pool (worker count from MODELBLASTER_POOL_THREADS).
    2. Resets every involved (model, backend) profile counter.
    3. Spawns one Zephyr worker per distinct core_kind, pinned to the
       schedule-assigned hart. Each worker walks the table in start-time
       order taking entries that match its kind.
    4. Inside the dispatch branch, selects the right per-backend table
       by ``core_kind`` and invokes ``MODEL_<UMID>_DISPATCH_FNS_<BS>``.
    5. Tracks per-network wall cycles inline (no model-side setter
       call — keeps wall-cycle bookkeeping backend-agnostic).
    6. Prints each network's final output between the standard
       ``=== MODELBLASTER_OUTPUT_BEGIN [<network>] ===`` markers so
       ``spike_runner`` can verify against the golden, plus per-backend
       profile records so post-run analysis can split per-op cycles by
       backend.
"""

from __future__ import annotations

import argparse
import json
import os
import re

# Match the ingest module's heuristic for splitting "<network><instance>".
# Falls back to the trailing-digits regex when no known set is provided.
# When known networks are available, longest-prefix match wins — this
# disambiguates model names ending in digits (e.g. "yolov8_nano_640"
# → ("yolov8_nano_64", 0), not ("yolov8_nano_", 640)).
_INSTANCE_RE = re.compile(r"^(?P<base>.+?)(?P<idx>\d+)$")


def _split_job_name(job: str, known: set[str] | None = None) -> tuple[str, int]:
    if known:
        for base in sorted(known, key=len, reverse=True):
            if job == base:
                return base, 0
            if job.startswith(base):
                rest = job[len(base):]
                if rest.isdigit():
                    return base, int(rest)
    m = _INSTANCE_RE.match(job)
    if not m:
        return job, 0
    return m.group("base"), int(m.group("idx"))


HEADER = "/* @generated by modelblaster/pipeline/generate_xpurt_main.py — do not edit. */"


def _c_ident(name: str) -> str:
    return name.replace(".", "_").replace("-", "_")


def _emit(networks: list[str], schedule_name: str,
          dispatch_table_header: str,
          core_kinds: list[str],
          backends: list[str],
          pool_sizes: list[int],
          n_instances: dict[str, int]) -> str:
    """Render xpurt_main.c source.

    `networks`     is the ordered list of distinct network names the
                   schedule references.
    `core_kinds`   is the ordered list of distinct core_kind values; one
                   scheduler-worker thread is spawned per kind.
    `backends`     is the ordered list of HW backends compiled into the
                   binary (== the per-model OBJECT-lib suffixes). Usually
                   identical to `core_kinds`, but separated to allow
                   binaries with backend pools larger than the schedule
                   used (e.g. a future fallback path).
    `pool_sizes`   is parallel to `core_kinds`; element k is the
                   modelblaster_pool_create() argument for kind k. modelblaster_pool's
                   thread count INCLUDES the calling thread, so a kind
                   with N harts wants pool_size=N (caller + N-1 helpers =
                   N total threads matching N harts). 0 ⇒ NULL pool;
                   parallel_<op> runs synchronously on the scheduler
                   worker. Intra-op parallelism kicks in only when a kind
                   has >=2 harts.
    `n_instances`  per-network instance count (max instance index + 1).
                   Sized arrays for wall-cycle bookkeeping so periodic
                   instances of the same network don't clobber each
                   other's start/elapsed scalars."""

    # State structs are emitted per (network, kind) so each worker's
    # `s.pool` is fixed at main() time. Without this, two workers that
    # dispatch concurrently into the same network race the per-dispatch
    # `s.pool` write, and the kernel ends up fanning out onto the wrong
    # kind's helpers. core_kinds covers everything the dispatcher
    # actually selects on; we union with backends for the (rare) case
    # where a backend has no matching kind in this schedule, so all
    # `s_<m>_<bs>` references in the bs_select branches resolve.
    all_kinds: list[str] = []
    for k in list(core_kinds) + list(backends):
        if k not in all_kinds:
            all_kinds.append(k)
    inc_lines: list[str] = []
    state_decls: list[str] = []
    state_inits: list[str] = []
    state_pool_assigns: list[str] = []
    output_buf_decls: list[str] = []
    forward_decls: list[str] = []
    reset_calls: list[str] = []
    branch_lines: list[str] = []
    print_blocks: list[str] = []
    wall_decls: list[str] = []

    for net in networks:
        mid = _c_ident(net)
        umid = mid.upper()
        n_inst = max(1, n_instances.get(net, 1))
        inc_lines.append(f'#include "{net}_model.h"')
        inc_lines.append(f'#include "{net}_test_io.h"')

        output_buf_decls.append(
            f"static model_{mid}_output_t out_{mid}[MODEL_{umid}_OUTPUT_SIZE];"
        )

        # One state struct per (network, kind). `.pool` is fixed in main()
        # before workers spawn, so the worker dispatch path never writes
        # to a struct shared across kinds. `.input` / `.output` are
        # read-only-from-the-worker after init; multiple kinds reading
        # them is safe. Intermediate buffers live in a per-model
        # buffers.c (extern) shared by every (network, kind), so
        # cross-kind dispatches in one network read each other's writes
        # exactly as they would in the straight-line path.
        for kind in all_kinds:
            state_decls.append(
                f"    model_{mid}_state_t s_{mid}_{kind};"
            )
            state_inits.append(
                f"    s_{mid}_{kind}.input  = model_{mid}_test_input;\n"
                f"    s_{mid}_{kind}.output = out_{mid};\n"
                f"    s_{mid}_{kind}.pool   = NULL;"
            )
            if kind in core_kinds:
                kind_idx = core_kinds.index(kind)
                state_pool_assigns.append(
                    f"    s_{mid}_{kind}.pool = pools[{kind_idx}];"
                )
            else:
                state_pool_assigns.append(
                    f"    s_{mid}_{kind}.pool = NULL;  /* {kind} not in core_kinds */"
                )

        # Per-instance wall-cycle bookkeeping. Periodic networks issue
        # multiple instances (`dronet0`, `dronet1`, ...) — sharing one
        # scalar would mean each instance overwrites the previous.
        wall_decls.append(
            f"static uint64_t wall_start_{mid}[{n_inst}] = {{ 0 }};")
        wall_decls.append(
            f"static uint64_t wall_cycles_{mid}[{n_inst}] = {{ 0 }};")

        # For each (model, backend) pair: forward-declare the per-backend
        # dispatch table + the renamed profile API. The harness CMakeLists
        # builds a separate OBJECT lib per pair so these live in distinct
        # TUs and link without collision.
        for bs in backends:
            BS = bs.upper()
            forward_decls.append(
                f"extern const model_{mid}_dispatch_fn "
                f"MODEL_{umid}_DISPATCH_FNS_{BS}[MODEL_{umid}_OP_COUNT];"
            )
            forward_decls.append(
                f"void model_{mid}_reset_profile_{bs}(void);")
            forward_decls.append(
                f"const model_{mid}_op_record_t *"
                f"model_{mid}_profile_records_{bs}(int *count);")
            reset_calls.append(f"    model_{mid}_reset_profile_{bs}();")

        # Build the per-backend selection inside the dispatch branch.
        # core_kind comes from the schedule and matches the backend tag;
        # we dispatch with the per-(network, kind) state struct so
        # `.pool` is the running kind's, with no per-dispatch write.
        #
        # Cross-tile memory coherence: Gemmini's RoCC DMA reads/writes
        # memory through an independent port at the SoC coherence point,
        # NOT through the CPU store buffer or L1 dcache. On
        # GemminiAndOPUShuttleConfig, the CPU on tile 0 (which dispatches
        # to Gemmini) might still have writes sitting in its store buffer
        # when Gemmini's mvin reads, and Gemmini's mvout writes may not
        # be visible to subsequent CPU loads on tile 1 (Saturn). The
        # `fence rw,rw` before+after each dispatch fixes both. Diagnosed
        # in merlin/third_party/iree_bar/.../embedded_elf_loader.c
        # (2026-05-14) and ported here for the multi-backend xpurt
        # dispatch loop. Without these fences, hetero output diverges
        # from golden (linf ~52 on dronet).
        # Dispatch branch: strcmp against the SCHEDULER'S core_kind (the
        # value the ingest stored in the table — registry kind), but
        # invoke through the BACKEND-suffixed dispatch fn symbol (which
        # is how each backend's per-model OBJECT lib is named). The two
        # can legitimately differ (e.g. kind="gemmini" → backend tag
        # "gemmini_q31") as long as they're paired by index in the
        # callsite's --core-kinds / --backends args. Before 2026-06-03
        # this loop strcmped against `bs` (the backend tag), so any
        # mismatch silently dropped every dispatch into the else clause
        # — verify then showed all-zero outputs (static init) and the
        # bug looked like FPGA corruption. The state struct stays
        # suffixed by `kind` so its .pool binding (in state_pool_assigns
        # above) keeps the kind's pool, regardless of the backend tag.
        if len(core_kinds) != len(backends):
            raise SystemExit(
                f"_emit: core_kinds and backends must have equal length "
                f"(got {core_kinds} vs {backends})"
            )
        bs_select_lines: list[str] = []
        for i, (kind, bs) in enumerate(zip(core_kinds, backends)):
            BS = bs.upper()
            kw = "if" if i == 0 else "else if"
            bs_select_lines.append(
                f'            {kw} (strcmp(e_->core_kind, "{kind}") == 0) {{\n'
                f"                __asm__ volatile(\"fence rw,rw\" ::: \"memory\");\n"
                f"                MODEL_{umid}_DISPATCH_FNS_{BS}[e_->dispatch_id](&s_{mid}_{kind});\n"
                f"                __asm__ volatile(\"fence rw,rw\" ::: \"memory\");\n"
                f"            }}"
            )
        bs_select_lines.append(
            "            else {\n"
            f'                printf("xpurt: FATAL unknown core_kind \'%s\' for {net} (entry %d) — '
            f'kind→backend mapping mismatch at codegen, see pipeline/generate_xpurt_main.py\\n", '
            f'e_->core_kind, e_->entry_id);\n'
            f"                sys_reboot(SYS_REBOOT_COLD);\n"
            "            }"
        )
        bs_select = "\n".join(bs_select_lines)

        branch_lines.append(
            f'        if (e_->network[0] == \'{net[0]}\' && '
            f'strcmp(e_->network, "{net}") == 0) {{\n'
            f"            /* Zero-cost IR ops (view, chunk2_c1) get\n"
            f"             * dispatch_id=-1 from ingest — they were\n"
            f"             * filtered out of the dispatch fn table by\n"
            f"             * generate_skeleton.py. Skip the kernel call\n"
            f"             * but still post the completion sem so any\n"
            f"             * dependents downstream unblock. */\n"
            f"            if (e_->dispatch_id < 0) {{\n"
            f"                /* Phase G2d producer-side fanout: give this\n"
            f"                 * entry's sem once per downstream consumer\n"
            f"                 * (data dep + time dep, dedup'd at ingest).\n"
            f"                 * Consumers take once with no re-give. Leaf\n"
            f"                 * entries (n_fanout=0) skip the give entirely. */\n"
            f"                for (int _f = 0; _f < e_->n_fanout; _f++) {{\n"
            f"                    k_sem_give(&completion_sems[i_]);\n"
            f"                }}\n"
            f"                prev_iter_end = (uint64_t)k_cycle_get_64();\n"
            f"                g_hart_acc[my_kind_idx].entries_done++;\n"
            f"                continue;\n"
            f"            }}\n"
            f"            if (e_->dispatch_id == 0) {{\n"
            f"                /* Honor the schedule's per-instance start\n"
            f"                 * time. Only enforced on dispatch_id==0 so\n"
            f"                 * subsequent ops still chain via data deps;\n"
            f"                 * this models periodic tasks waking at\n"
            f"                 * deterministic boundaries (e.g. mlp_control\n"
            f"                 * every 5 ms) without forcing the rest of\n"
            f"                 * the instance into lockstep. */\n"
            f"                uint64_t target_start = run_t0 +\n"
            f"                    (uint64_t)((double)e_->start_time_ms *\n"
            f"                               (double)XPURT_CYCLES_PER_MS);\n"
            f"                uint64_t t_gate0 = (uint64_t)k_cycle_get_64();\n"
            f"                while ((uint64_t)k_cycle_get_64() < target_start) {{\n"
            f"                    k_yield();\n"
            f"                }}\n"
            f"                g_hart_acc[my_kind_idx].target_gate_spin +=\n"
            f"                    ((uint64_t)k_cycle_get_64() - t_gate0);\n"
            + "\n".join(
                f"                model_{mid}_reset_profile_{bs}();"
                for bs in backends
            ) + "\n"
            f"                wall_start_{mid}[e_->instance] = (uint64_t)k_cycle_get_64();\n"
            f"            }}\n"
            f"            uint64_t t_disp0 = (uint64_t)k_cycle_get_64();\n"
            f"#ifdef MODELBLASTER_XPURT_TRACE\n"
            f"            xpurt_trace[i_].start_cycles = t_disp0 - run_t0;\n"
            f"#endif\n"
            f"{bs_select}\n"
            f"            uint64_t t_disp1 = (uint64_t)k_cycle_get_64();\n"
            f"            g_hart_acc[my_kind_idx].kernel += (t_disp1 - t_disp0);\n"
            f"#ifdef MODELBLASTER_XPURT_TRACE\n"
            f"            xpurt_trace[i_].end_cycles = t_disp1 - run_t0;\n"
            f"            xpurt_trace[i_].worker_kind_idx = my_kind_idx;\n"
            f"#endif\n"
            f"            if (e_->dispatch_id == MODEL_{umid}_OP_COUNT - 1) {{\n"
            f"                wall_cycles_{mid}[e_->instance] =\n"
            f"                    (uint64_t)k_cycle_get_64() - wall_start_{mid}[e_->instance];\n"
            f"            }}\n"
            f"            /* Phase G2d: producer-side fanout. Give this\n"
            f"             * entry's sem once per downstream consumer; the\n"
            f"             * consumer-side take loop does NOT re-give (saves\n"
            f"             * one sem op per dep edge). Leaf entries skip the\n"
            f"             * give entirely. */\n"
            f"            for (int _f = 0; _f < e_->n_fanout; _f++) {{\n"
            f"                k_sem_give(&completion_sems[i_]);\n"
            f"            }}\n"
            f"            uint64_t t_iter_end = (uint64_t)k_cycle_get_64();\n"
            f"            g_hart_acc[my_kind_idx].sync_overhead += (t_iter_end - t_disp1);\n"
            f"            prev_iter_end = t_iter_end;\n"
            f"            g_hart_acc[my_kind_idx].entries_done++;\n"
            f"            continue;\n"
            f"        }}"
        )

        # Per-backend profile record dump. Each backend's TU has its own
        # records array; entries that ran on backend X land in X's array.
        # We tag rows with the backend so the host can split per-op cost
        # by backend.
        per_bs_profile_blocks: list[str] = []
        for bs in backends:
            per_bs_profile_blocks.append(f"""\
        {{
            int n_records = 0;
            const model_{mid}_op_record_t *records =
                model_{mid}_profile_records_{bs}(&n_records);
            for (int i = 0; i < n_records; i++) {{
                printf("{bs},%d,%s,%s,%s,%lu\\n",
                       records[i].dispatch_id,
                       records[i].name, records[i].op, records[i].shape,
                       records[i].cycles);
            }}
        }}""")
        per_bs_profile = "\n".join(per_bs_profile_blocks)

        # Per-instance wall-cycles dump under a NEW marker so streamed
        # runners (firesim_runner, spike_runner) that count
        # `=== MODELBLASTER_WALL_CYCLES [<net>] === <int>` for end-of-run
        # detection still see exactly one bare WALL_CYCLES per network
        # below. The per-instance variant uses
        # `=== MODELBLASTER_WALL_CYCLES_INST [<net>#<i>] ===` and is captured
        # for analysis by the host parser.
        # Output dump strategy: HTIF UART throughput is ~6 KB/sec on
        # FireSim Saturn. Dumping every output value as ASCII works for
        # small models (dronet: 2 values, mlp_control: 4) but is the
        # workflow bottleneck for yolov8-scale outputs (75600 values
        # blow well past the FIRESIM_TIMEOUT). For large outputs we
        # emit a *sampled* dump — first 8, last 8, plus a checksum/L1
        # summary for spot-check parity — and rely on per-model unit
        # tests (or a separate dedicated verify run) for full
        # bit-exactness. The marker tags stay the same so existing
        # parsers continue to find OUTPUT_BEGIN/END.
        print_blocks.append(f"""\
    printf("=== MODELBLASTER_OUTPUT_BEGIN [{net}] ===\\n");
    {{
        const int _osz = MODEL_{umid}_OUTPUT_SIZE;
        const int _SAMPLE_THRESHOLD = 64;
        if (_osz <= _SAMPLE_THRESHOLD) {{
            for (int i = 0; i < _osz; i++)
                printf("%.9g\\n", (double)out_{mid}[i]);
        }} else {{
            /* Sampled dump + summary. */
            double _sum = 0.0, _abs_sum = 0.0;
            double _omax = -1.0/0.0, _omin = 1.0/0.0;
            for (int i = 0; i < _osz; i++) {{
                double v = (double)out_{mid}[i];
                _sum += v;
                _abs_sum += (v < 0) ? -v : v;
                if (v > _omax) _omax = v;
                if (v < _omin) _omin = v;
            }}
            printf("OUTPUT_SAMPLED size=%d head=8 tail=8\\n", _osz);
            for (int i = 0; i < 8; i++)
                printf("  [%d] %.9g\\n", i, (double)out_{mid}[i]);
            for (int i = _osz - 8; i < _osz; i++)
                printf("  [%d] %.9g\\n", i, (double)out_{mid}[i]);
            printf("OUTPUT_SUMMARY sum=%.6g abs_sum=%.6g min=%.6g max=%.6g\\n",
                   _sum, _abs_sum, _omin, _omax);
        }}
    }}
    printf("=== MODELBLASTER_OUTPUT_END [{net}] ===\\n");
    printf("=== MODELBLASTER_PROFILE_BEGIN [{net}] ===\\n");
    printf("backend,dispatch_id,name,op,shape,cycles\\n");
{per_bs_profile}
    printf("=== MODELBLASTER_PROFILE_END [{net}] ===\\n");
    {{
        unsigned long _max_wc = 0;
        for (int _i = 0; _i < {n_inst}; _i++) {{
            unsigned long _wc = (unsigned long)wall_cycles_{mid}[_i];
            printf("=== MODELBLASTER_WALL_CYCLES_INST [{net}#%d] === %lu\\n",
                   _i, _wc);
            if (_wc > _max_wc) _max_wc = _wc;
        }}
        /* Worst-case per-instance wall cycles — meaningful for periodic
         * tasks (highest observed latency) and identical to the single
         * value for non-periodic networks. */
        printf("=== MODELBLASTER_WALL_CYCLES [{net}] === %lu\\n", _max_wc);
    }}""")

    upper = schedule_name.replace(".", "_").replace("-", "_").upper()

    # Build the per-(network, instance, dispatch_id) dispatch branch.
    dispatch_branch = "\n".join(branch_lines)

    # One Zephyr worker thread per distinct core_kind. Each pins itself
    # to a hart (the entry's .hart) and pulls only entries whose
    # core_kind matches.
    n_kinds = len(core_kinds)
    kind_strs = ", ".join(f'"{k}"' for k in core_kinds)
    if len(pool_sizes) != n_kinds:
        raise SystemExit(
            f"pool_sizes length ({len(pool_sizes)}) must match core_kinds "
            f"length ({n_kinds})")
    pool_size_strs = ", ".join(str(s) for s in pool_sizes)

    # Forward decls go right after the model headers — they reference
    # types from those headers (model_<mid>_dispatch_fn etc.).
    forward_decl_block = "\n".join(forward_decls)

    return f"""{HEADER}
/*
 * Schedule-driven multi-network entry point with per-core-kind worker
 * threads and HETEROGENEOUS per-backend dispatch tables. Each worker:
 *   1. Walks the XPU-RT-emitted dispatch table in start_time order,
 *      taking entries whose .core_kind matches its own kind.
 *   2. Before invoking, waits on k_sems posted by the producers of its
 *      .deps[] (intra-job data deps) and .time_dep_entry_id (cross-job
 *      ordering edges).
 *   3. Selects the per-(model, backend) dispatch table by .core_kind
 *      and invokes the matching kernel. backend_rename.py at compile
 *      time has suffixed every model's externally-visible symbol with
 *      _<bs>, so multiple backends per model link cleanly.
 *   4. After invoking, gives the entry's k_sem so consumers unblock.
 * Workers are pinned to harts via pthread_attr_setaffinity_np (Phase A
 * patch). modelblaster_pool is the parallel-for primitive — parallel_<op>
 * wrappers inside dispatched kernels use it for intra-op parallelism.
 *
 * Outputs follow the same multi-line marker protocol as the
 * straight-line multi_main, so spike_runner verifies them against
 * PyTorch goldens unchanged. The PROFILE block now has a leading
 * `backend` column so per-op cycles can be split per backend.
 */

#define MODELBLASTER_DISABLE_UNMANGLED

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <sched.h>
#include "modelblaster_pool.h"
#include <zephyr/kernel.h>      /* k_cycle_get_64, k_sem */
#include <zephyr/sys/reboot.h>

{chr(10).join(inc_lines)}
#include "{dispatch_table_header}"

/* Note (2026-05-28): we previously tried several memory-fence and
 * cache-invalidation strategies to fix `dronet_hetero` verify-fail
 * (max_abs_err=52 vs golden). All failed identically:
 *
 *   - fence rw,rw before+after each dispatch:    output unchanged
 *   - L1 dcache eviction via 128KB scratch read: output unchanged
 *   - Zicbom cbo.inval:                          illegal-instr trap
 *     (mcause=2, mtval=0x7a00f) -- bitstream
 *     was not built with Zicbom.
 *
 * Persistent identical failure across these very different remedies
 * indicates the bug is NOT cross-tile cache staleness. The real
 * cause is cross-backend per-op numerical drift: gemmini and
 * rvv_opu each match PyTorch golden bit-exactly END-TO-END, but
 * their intermediate per-op outputs differ slightly due to
 * backend-specific rounding/quantization details (each backend's
 * full chain happens to cancel its own drift into a golden-matching
 * final answer; mixing chains doesn't preserve that property).
 *
 * Documented in notes/known_issues.md. Fix path is cross-backend
 * numerical alignment, not memory mgmt. fence rw,rw is kept on the
 * dispatch boundaries below as good hygiene (it WAS load-bearing
 * for Gemmini DMA in merlin's loader; harmless and ~zero cost). */

/* Per-(model, backend) externs — the harness compiles a separate
 * OBJECT lib per pair, with externally-visible symbols suffixed _<bs>
 * via -D renames (see modelblaster/pipeline/backend_rename.py). */
{forward_decl_block}

{chr(10).join(output_buf_decls)}

/* Per-entry completion sem: posted once when the dispatch finishes;
 * dependents take it before invoking. Initialized as 0/1 (binary, but
 * grow the limit so multiple consumers can each take their own
 * "completed" reading without blocking each other). */
static struct k_sem completion_sems[{upper}_N_ENTRIES];

/* Phase G1 — per-hart runtime attribution counters, accumulated in
 * mtime ticks (1 us each on chipyard FireSim). Read at end-of-run and
 * dumped under MODELBLASTER_HART_ACC for host-side decomposition of
 * the predicted-vs-measured wall gap. Indexed by my_kind_idx. */
#ifndef XPURT_MAX_KINDS
#define XPURT_MAX_KINDS 8
#endif
struct xpurt_hart_acc {{
    uint64_t kernel;            /* mtime delta around bs_select dispatch */
    uint64_t dep_wait;          /* mtime inside k_sem_take loop */
    uint64_t sync_overhead;     /* mtime between kernel-end and end of iter */
    uint64_t target_gate_spin;  /* mtime inside dispatch_id==0 spin */
    uint64_t hart_idle;         /* mtime between iters (gap to next match) */
    uint64_t gemmini_cfg_emit;  /* reserved for G2b caching wrappers */
    uint64_t entries_done;      /* count of dispatched entries */
    uint64_t wall_total;        /* worker_t0 → worker_exit delta */
}};
static struct xpurt_hart_acc g_hart_acc[XPURT_MAX_KINDS];

/* One state struct per (network, kind). `.pool` is bound to the kind's
 * modelblaster_pool in main() before workers spawn and never written again
 * by the worker — that eliminates the data race that existed when a
 * single shared `s_<m>` had its `.pool` rewritten per-dispatch by
 * whichever worker happened to take the entry. Two workers dispatching
 * independent ops in the same network now each pass their own
 * (network, kind) state pointer, so `s->pool` always names the running
 * kind's helpers. Intermediate buffers are file-static, shared across
 * all (network, kind) state structs of one network — see the comments
 * over `extern int8_t buf_<mid>_*` in each model.c. */
{chr(10).join("static " + d.lstrip() for d in state_decls).rstrip()}

/* Per-instance wall-clock state. Each periodic instance writes its own
 * slot indexed by entry->instance, so back-to-back instances of one
 * network don't clobber each other's start/elapsed scalars. */
{chr(10).join(wall_decls)}

/* Per-kind intra-op pool. Set up in main() before workers spawn, then
 * each (network, kind) state struct's `.pool` is bound to the matching
 * `pools[k]` once. NULL ⇒ kind has only 1 hart, so parallel_<op>
 * wrappers run synchronously on the calling scheduler worker. Type
 * erased to void* here so the same generated source remained
 * backend-agnostic during the migration; modelblaster_pool is the only path
 * now. */
static void *pools[{n_kinds}] = {{ NULL }};

/* mtime baseline for the run, captured immediately before workers spawn.
 * Used by the worker to (a) honor per-instance schedule start times for
 * periodic networks (gating dispatch_id==0 entries until run_t0 +
 * start_time_ms), and (b) tag actual_start/end_cycles in the trace. */
static uint64_t run_t0;
#define XPURT_CYCLES_PER_MS \\
    ((uint64_t)(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC / 1000))

#ifdef MODELBLASTER_XPURT_TRACE
/* Per-entry execution trace. Each slot is touched by exactly one
 * worker (the one whose core_kind matches) so concurrent writes never
 * overlap. Cycles are mtime-based (k_cycle_get_64) and offset against
 * `run_t0`, captured immediately before the first worker starts. The
 * host parser reconstructs (start_ms, end_ms) by dividing by the
 * configured clock_mhz. */
struct xpurt_trace_slot {{
    uint64_t start_cycles;
    uint64_t end_cycles;
    int      worker_kind_idx;   /* index into kinds[] */
}};
static struct xpurt_trace_slot xpurt_trace[{upper}_N_ENTRIES];
#endif

struct xpurt_worker_arg {{
    const char *kind;
    int hart;
    int kind_idx;
}};

static void *xpurt_worker(void *arg)
{{
    struct xpurt_worker_arg *wa = (struct xpurt_worker_arg *)arg;
    const char *my_kind = wa->kind;
    int my_kind_idx = wa->kind_idx;
    /* Phase G1 attribution: track per-iter timing so we can decompose
     * wall_total into kernel + dep_wait + sync_overhead +
     * target_gate_spin + hart_idle. prev_iter_end is updated INSIDE
     * each per-net branch just before `continue` so hart_idle on the
     * next iter is correctly (this_iter_start - last_iter_end). */

    /* Per-hart V-extension enable. Zephyr's HAS_V() macro reads
     * misa from the PRIMARY hart only — on our 2-tile
     * FireSimGemminiAndOPUShuttleConfig that's hart 0 (Rocket +
     * Gemmini, misa.V=0) so Zephyr leaves mstatus.VS = Off
     * EVERYWHERE, including on hart 1 (Shuttle + Saturn-OPU) which
     * does have V (misa.V=1, verified by examples/opu_probe). If we
     * don't flip VS to Initial here, the first vsetvli in any RVV
     * kernel dispatched to this hart traps with illegal-instruction.
     *
     * Behavior: read THIS hart's misa, and if the V bit is set,
     * raise mstatus.VS to Initial (writes to mstatus.VS are silently
     * ignored on harts whose misa.V=0, so this is a no-op on
     * non-V harts and safe to run unconditionally per worker). */
    {{
        unsigned long _misa;
        asm volatile("csrr %0, misa" : "=r"(_misa));
        if (_misa & (1UL << 21)) {{  /* 'V' - 'A' = 21 */
            unsigned long _vs_init = (1UL << 9);  /* MSTATUS_VS = Initial */
            asm volatile("csrs mstatus, %0" : : "r"(_vs_init));
        }}
    }}

    uint64_t worker_t0 = (uint64_t)k_cycle_get_64();
    uint64_t prev_iter_end = worker_t0;
    /* Take entries that match `my_kind`, in start_time order. */
    for (int i_ = 0; i_ < {upper}_N_ENTRIES; i_++) {{
        const xpurt_sched_entry_t *e_ = &{upper}_TABLE[i_];
        if (strcmp(e_->core_kind, my_kind) != 0) continue;

        uint64_t t_iter_start = (uint64_t)k_cycle_get_64();
        if (g_hart_acc[my_kind_idx].entries_done > 0) {{
            g_hart_acc[my_kind_idx].hart_idle +=
                (t_iter_start - prev_iter_end);
        }}

        /* Wait for all data deps + the time_dep edge to complete.
         * Phase G2d: producer gives its sem once per UNIQUE consumer
         * (dedup'd at ingest), consumer takes once per UNIQUE dep
         * here. No re-give — the counts balance. The time_dep edge
         * dedup against deps[] preserves the invariant when one
         * producer is both a data and a time dep of the same
         * consumer (without dedup, consumer takes twice from one
         * producer give → deadlock). */
        for (int d = 0; d < e_->n_deps; d++) {{
            k_sem_take(&completion_sems[e_->deps[d]], K_FOREVER);
        }}
        if (e_->time_dep_entry_id >= 0) {{
            int _td_is_dup = 0;
            for (int _d = 0; _d < e_->n_deps; _d++) {{
                if (e_->deps[_d] == e_->time_dep_entry_id) {{
                    _td_is_dup = 1;
                    break;
                }}
            }}
            if (!_td_is_dup) {{
                k_sem_take(&completion_sems[e_->time_dep_entry_id], K_FOREVER);
            }}
        }}
        uint64_t t_deps_done = (uint64_t)k_cycle_get_64();
        g_hart_acc[my_kind_idx].dep_wait += (t_deps_done - t_iter_start);

{dispatch_branch}
        printf("xpurt: WARN unknown network %s in entry %d\\n",
               e_->network, e_->entry_id);
        /* Unknown network — give the sem anyway so we don't deadlock.
         * Fan out per the producer-side invariant so any downstream
         * consumers actually unblock. */
        for (int _f = 0; _f < e_->n_fanout; _f++) {{
            k_sem_give(&completion_sems[i_]);
        }}
        prev_iter_end = (uint64_t)k_cycle_get_64();
        g_hart_acc[my_kind_idx].entries_done++;
    }}
    g_hart_acc[my_kind_idx].wall_total =
        (uint64_t)k_cycle_get_64() - worker_t0;
    return NULL;
}}

int main(void)
{{
    printf("xpurt-runner: schedule={schedule_name} entries=%d kinds=%d on %s\\n",
           {upper}_N_ENTRIES, {n_kinds}, CONFIG_BOARD_TARGET);

    /* Per-kind modelblaster_pool sizes. Element k's helper thread count is
     * (harts_of_kind_k - 1) — one less than the kind's hart count, since
     * the scheduler-worker thread for that kind is itself one of those
     * harts. 0 ⇒ NULL pool, parallel_<op> wrappers run synchronously on
     * the calling scheduler worker. We never oversubscribe a backend's
     * harts; on real silicon this maps each pool's helper threads onto
     * the kind's idle harts. */
    static const int pool_sizes[{n_kinds}] = {{ {pool_size_strs} }};
    for (int k = 0; k < {n_kinds}; k++) {{
        if (pool_sizes[k] > 0) {{
            pools[k] = (void *)modelblaster_pool_create(pool_sizes[k]);
            if (pools[k] == NULL) {{
                printf("FATAL: modelblaster_pool_create kind=%d size=%d failed\\n",
                       k, pool_sizes[k]);
                sys_reboot(SYS_REBOOT_COLD);
                return -1;
            }}
        }}
        printf("modelblaster_pool[kind=%d]: %u helpers (intra-op)\\n",
               k, (unsigned)(pools[k] ? modelblaster_pool_get_threads_count((modelblaster_pool_t)pools[k]) : 0));
    }}

{chr(10).join(state_inits)}

    /* Bind each (network, kind) state struct's `.pool` to the matching
     * `pools[k]`. Done once here, before workers spawn — the worker
     * dispatch path no longer writes to `s_<m>_<kind>.pool`. */
{chr(10).join(state_pool_assigns)}

{chr(10).join(reset_calls)}

    /* Init completion sems. Limit needs to be >= max fanout across
     * all entries (producer gives n_fanout times before any consumer
     * has taken). For our schedules max fanout is observed at <16; a
     * 32 cap gives headroom while keeping the sem accounting tight
     * (Phase G2d). The old limit=64 + take/re-give pattern is gone. */
    for (int i = 0; i < {upper}_N_ENTRIES; i++) {{
        k_sem_init(&completion_sems[i], 0, 32);
    }}

    /* One worker per distinct core_kind. Each pins itself to the first
     * matching entry's hart (good enough — assumes all entries of the
     * same kind share a hart, which is true for our singleton-machine
     * schedules; multi-hart-per-kind would need a per-hart subdivision).
     *
     * Zephyr quirk: pthread_attr_init() casts the public pthread_attr_t*
     * to the internal `struct posix_thread_attr*` and zeroes it; with
     * CONFIG_POSIX_THREADS_AFFINITY the internal struct extends past the
     * public 16 bytes (cpu_affinity sits at offset 16). Without padding,
     * pthread_attr_setaffinity_np(&attrs[k+1]) silently corrupts the
     * adjacent wargs[k]. Pad each slot to 64 bytes so the cast stays in
     * its lane. */
    static const char *kinds[] = {{ {kind_strs} }};
    static struct xpurt_worker_arg wargs[{n_kinds}];
    static pthread_t tids[{n_kinds}];
    union xpurt_attr_slot {{ pthread_attr_t a; char _pad[64]; }};
    static union xpurt_attr_slot attrs[{n_kinds}];

    /* Run baseline for both the trace and the periodic-start-time gate.
     * Captured just before workers spawn so it's the moment "t=0" of the
     * schedule maps to. */
    run_t0 = (uint64_t)k_cycle_get_64();

    for (int k = 0; k < {n_kinds}; k++) {{
        int pinned_hart = -1;
        for (int i_ = 0; i_ < {upper}_N_ENTRIES; i_++) {{
            if (strcmp({upper}_TABLE[i_].core_kind, kinds[k]) == 0) {{
                pinned_hart = {upper}_TABLE[i_].hart;
                break;
            }}
        }}
        wargs[k].kind = kinds[k];
        wargs[k].hart = pinned_hart;
        wargs[k].kind_idx = k;

        pthread_attr_init(&attrs[k].a);
#ifdef CONFIG_POSIX_THREADS_AFFINITY
        if (pinned_hart >= 0) {{
            cpu_set_t cs;
            CPU_ZERO(&cs);
            CPU_SET(pinned_hart, &cs);
            pthread_attr_setaffinity_np(&attrs[k].a, sizeof(cs), &cs);
        }}
#endif
        int rc = pthread_create(&tids[k], &attrs[k].a, xpurt_worker, &wargs[k]);
        if (rc != 0) {{
            printf("FATAL: pthread_create kind=%s rc=%d\\n", kinds[k], rc);
            sys_reboot(SYS_REBOOT_COLD);
            return -1;
        }}
        /* Per-worker spawn diagnostic deferred to after pthread_join.
         * Inline printf here costs ~tens-of-ms over FireSim HTIF UART
         * and starves any worker pinned to the same hart as main
         * (the scalar worker pinned to hart 0). The (kind, pinned_hart)
         * info is already aggregated in wargs[k]; print at the end so
         * it doesn't perturb the schedule's actual_start cycle counts. */
    }}

    /* Wait for every worker to drain. */
    for (int k = 0; k < {n_kinds}; k++) {{
        pthread_join(tids[k], NULL);
        pthread_attr_destroy(&attrs[k].a);
    }}

    /* Now safe to flush the spawn diagnostics — workers are done, so
     * nothing pinned to hart 0 is competing with main for UART time. */
    for (int k = 0; k < {n_kinds}; k++) {{
        printf("xpurt: worker[%d] kind=%s pinned_hart=%d\\n",
               k, wargs[k].kind, wargs[k].hart);
    }}

    /* Phase G1 — per-hart runtime attribution. All values are mtime
     * ticks (1 us each on chipyard FireSim). Sum of categories should
     * equal wall_total within ~2%; residual is unattributed overhead
     * (k_cycle_get_64 itself, branch mispredict, etc.). */
    printf("=== MODELBLASTER_HART_ACC_BEGIN ===\\n");
    printf("kind_idx,kind,kernel_us,dep_wait_us,sync_overhead_us,"
           "target_gate_spin_us,hart_idle_us,gemmini_cfg_emit_us,"
           "entries_done,wall_total_us\\n");
    for (int k = 0; k < {n_kinds}; k++) {{
        printf("%d,%s,%llu,%llu,%llu,%llu,%llu,%llu,%llu,%llu\\n",
               k, kinds[k],
               (unsigned long long)g_hart_acc[k].kernel,
               (unsigned long long)g_hart_acc[k].dep_wait,
               (unsigned long long)g_hart_acc[k].sync_overhead,
               (unsigned long long)g_hart_acc[k].target_gate_spin,
               (unsigned long long)g_hart_acc[k].hart_idle,
               (unsigned long long)g_hart_acc[k].gemmini_cfg_emit,
               (unsigned long long)g_hart_acc[k].entries_done,
               (unsigned long long)g_hart_acc[k].wall_total);
    }}
    printf("=== MODELBLASTER_HART_ACC_END ===\\n");

#ifdef MODELBLASTER_XPURT_TRACE
    /* Trace dump — one CSV row per scheduled entry, with the actual
     * mtime-cycle window the worker ran and the kind-index of the
     * worker that owned it. The host parser cross-references this
     * with the dispatch table for op/network/predicted-time fields. */
    printf("=== MODELBLASTER_XPURT_TRACE_BEGIN ===\\n");
    printf("entry_id,network,instance,dispatch_id,op,name,core_kind,hart,"
           "predicted_start_ms,predicted_duration_ms,worker_kind_idx,"
           "actual_start_cycles,actual_end_cycles\\n");
    for (int i = 0; i < {upper}_N_ENTRIES; i++) {{
        const xpurt_sched_entry_t *e = &{upper}_TABLE[i];
        printf("%d,%s,%d,%d,%s,%s,%s,%d,%.6f,%.6f,%d,%llu,%llu\\n",
               e->entry_id, e->network, e->instance, e->dispatch_id,
               e->op, e->name, e->core_kind, e->hart,
               (double)e->start_time_ms, (double)e->duration_ms,
               xpurt_trace[i].worker_kind_idx,
               (unsigned long long)xpurt_trace[i].start_cycles,
               (unsigned long long)xpurt_trace[i].end_cycles);
    }}
    printf("=== MODELBLASTER_XPURT_TRACE_END ===\\n");
#endif

{chr(10).join(print_blocks)}

    for (int k = 0; k < {n_kinds}; k++) {{
        if (pools[k] != NULL) {{
            modelblaster_pool_destroy((modelblaster_pool_t)pools[k]);
        }}
    }}
    sys_reboot(SYS_REBOOT_COLD);
    return 0;
}}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--schedule", required=True,
                    help="path to the schedule.json (XPU-RT format)")
    ap.add_argument("--out", required=True,
                    help="path to write xpurt_main.c")
    ap.add_argument("--name", required=True,
                    help="schedule name — must match the --name passed to "
                         "ingest_xpurt_schedule (drives the table symbol prefix)")
    ap.add_argument("--dispatch-table-header", required=True,
                    help="basename of the .h emitted by ingest_xpurt_schedule "
                         "(included from xpurt_main.c)")
    ap.add_argument("--core-kinds", default="rvv,scalar",
                    help="comma list of distinct core_kind values the schedule "
                         "uses. One worker thread is spawned per kind. "
                         "(default: rvv,scalar)")
    ap.add_argument("--backends", default=None,
                    help="comma list of HW backends the harness was compiled "
                         "for (== per-model OBJECT-lib suffixes). The walker "
                         "forward-declares MODEL_<UMID>_DISPATCH_FNS_<BS> for "
                         "each backend and dispatches by core_kind. "
                         "Defaults to --core-kinds.")
    ap.add_argument("--registry", default=None,
                    help="path to the cores/*.json registry that drove the "
                         "schedule. Used to derive each kind's pool size as "
                         "(harts_of_kind - 1). If both --registry and "
                         "--pool-sizes are absent, all kinds get pool=0 "
                         "(NULL) and intra-op parallel_<op> calls run "
                         "synchronously on the scheduler worker.")
    ap.add_argument("--pool-sizes", default=None,
                    help='explicit per-kind pool helper-thread count, '
                         'e.g. "rvv:0,scalar:0". Overrides --registry. '
                         "Use 0 for kinds with one hart (NULL pool).")
    args = ap.parse_args()

    with open(args.schedule) as f:
        sched = json.load(f)
    networks: list[str] = []
    seen: set[str] = set()
    n_instances: dict[str, int] = {}
    # Multi-network bridge stamps an explicit instances list in
    # provenance — use it when present (it's the only way to be
    # unambiguous about model names ending in digits, e.g. "yolov8_nano_64"
    # which the trailing-digits regex parses as "yolov8_nano_" + idx=64).
    prov_instances = sched.get("_provenance", {}).get("instances")
    if prov_instances:
        known = {ins["network"] for ins in prov_instances}
        for ins in prov_instances:
            net = ins["network"]
            inst = ins["instance"]
            if net not in seen:
                seen.add(net)
                networks.append(net)
            n_instances[net] = max(n_instances.get(net, 0), inst + 1)
    else:
        known = None
        for d in sched["dispatches"].values():
            net, inst = _split_job_name(d["job_name"], known)
            if net not in seen:
                seen.add(net)
                networks.append(net)
            n_instances[net] = max(n_instances.get(net, 0), inst + 1)

    core_kinds = [k.strip() for k in args.core_kinds.split(",") if k.strip()]
    if not core_kinds:
        raise SystemExit("--core-kinds must be a non-empty comma list")
    if args.backends is None:
        backends = list(core_kinds)
    else:
        backends = [b.strip() for b in args.backends.split(",") if b.strip()]
        if not backends:
            raise SystemExit("--backends must be a non-empty comma list")

    # Guard against the silent-dispatch-drop bug (2026-06-03):
    # the schedule's dispatch table carries .core_kind = registry-kind
    # (e.g. "gemmini"). The generated dispatch branch must strcmp the
    # entry's .core_kind against the SAME string — so kind→backend
    # mapping is now done by zip(core_kinds, backends) inside _emit
    # (strcmp uses kind, dispatch fn symbol uses backend). Asserting
    # length parity here so the index-aligned mapping is well-defined.
    if len(core_kinds) != len(backends):
        raise SystemExit(
            f"--core-kinds and --backends must have the same length "
            f"(got core_kinds={core_kinds}, backends={backends}). The "
            f"dispatch branch pairs kind[i] -> backend[i] by index."
        )

    # Pool size resolution:
    #   1. explicit --pool-sizes wins
    #   2. else --registry: harts_of_kind - 1 per kind
    #   3. else default 0 per kind (NULL pool, no intra-op fanout)
    pool_sizes_map: dict[str, int] = {}
    if args.pool_sizes:
        for kv in args.pool_sizes.split(","):
            k, _, v = kv.strip().partition(":")
            if not k or not v:
                raise SystemExit(f"--pool-sizes: bad entry '{kv}'")
            pool_sizes_map[k] = int(v)
    elif args.registry:
        with open(args.registry) as f:
            reg = json.load(f)
        harts_per_kind: dict[str, set[int]] = {}
        for c in reg.get("cores", []):
            kind = c.get("kind")
            harts = c.get("harts", []) or []
            if kind is None:
                continue
            harts_per_kind.setdefault(kind, set()).update(harts)
        for k in core_kinds:
            n_harts = len(harts_per_kind.get(k, set()))
            # modelblaster_pool_create(N) makes a pool of N threads INCLUDING
            # the caller, so use n_harts directly. 1-hart kinds still get
            # 0 (NULL pool, serial fallback) since create(1) just allocates
            # a degenerate pool with no helpers.
            pool_sizes_map[k] = n_harts if n_harts >= 2 else 0
    pool_sizes = [pool_sizes_map.get(k, 0) for k in core_kinds]

    src = _emit(networks, args.name, args.dispatch_table_header,
                core_kinds, backends, pool_sizes, n_instances)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(src)
    print(f"wrote {args.out}  (networks: {networks} "
          f"instances: {n_instances} kinds: {core_kinds} "
          f"backends: {backends} pool_sizes: {pool_sizes})")


if __name__ == "__main__":
    main()
