"""Ingest an XPU-RT-emitted schedule.json -> combined C dispatch table.

XPU-RT's schedule is a multi-network table:

    {
      "dot_file": "...",
      "dispatches": {
        "<job_name>_dispatch_<id>": {
          "id": <int>,
          "ordinal": 1, "total": 1,
          "dependencies": ["<other key>", ...],   // intra-job data deps
          "hardware_target": "CPU_P#0" | "CPU_E#0",
          "start_time": <ms>, "duration": <ms>,
          "job_name": "dronet" | "mlp_control0" | ...,
          "module_name": "...",
          "time_dependency": "<other key>"          // optional cross-job edge
        }, ...
      }
    }

This module:

  1. Parses the schedule, groups dispatches by job_name.
  2. Validates each (job_name, id) against the corresponding model's
     graph.json — the id must reference a real dispatch in the IR.
     Multiple instances of the same network (e.g. mlp_control0..5) all
     share one IR.
  3. Resolves the cross-job time_dependency field — the scheduler can
     issue these to serialize independent jobs across cores.
  4. Maps `CPU_P#<N>` / `CPU_E#<N>` to a core name from a user-provided
     mapping (cpu_p_kind, cpu_e_kind), then to a registry entry whose
     harts pin the runtime worker. Default: cpu_p_kind=rvv, cpu_e_kind=scalar.
  5. Emits `<schedule>_dispatch_table.{h,c}` containing one entry per
     XPU-RT dispatch, ordered by start_time. The runtime walks this
     table to drive execution.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import dataclass
from typing import Optional

from modelblaster.pipeline import core_registry


HEADER = "/* @generated by modelblaster/pipeline/ingest_xpurt_schedule.py — do not edit. */"


@dataclass
class XpurtEntry:
    entry_id: int               # 0..N-1 (table position after sort)
    schedule_key: str           # original JSON key, e.g. "mlp_control3_dispatch_0"
    job_name: str               # e.g. "mlp_control3"
    network: str                # e.g. "mlp_control" (instance suffix stripped)
    instance: int               # 0 for unique networks; 0..K-1 for periodic
    dispatch_id: int            # IR-side dispatch_id within `network`
    op: str                     # echo from IR (linear, conv2d, ...)
    name: str                   # echo from IR (e.g. "mlp.0")
    core_name: str              # registry core name (e.g. "rvv0" or "rocket0")
    core_kind: str              # registry kind (e.g. "rvv", "scalar")
    impl: str                   # kernel implementation to invoke for THIS
                                # dispatch ("rvv" / "ime" / ...). Defaults to
                                # core_kind, which is what every schedule
                                # written before `scheduler.enable_impls`
                                # existed means. See `load()`.
    hart: int                   # preferred hart (from registry); -1 if unbound
    harts: tuple[int, ...]      # every hart reserved by hardware_target;
                                # first element is the dispatch-owning master
    start_time_ms: float
    duration_ms: float
    deps_entry_ids: tuple[int, ...]   # in-table entry_ids of intra-job deps
    time_dep_entry_id: int            # cross-job edge, -1 if none
    # Producer-side fanout (Phase G2d): list of entry_ids that consume
    # *this* entry's output, via either a data-dep edge (their
    # deps_entry_ids includes self.entry_id) or a time-dep edge
    # (their time_dep_entry_id == self.entry_id). Computed by load()
    # after deps are resolved. The walker uses this to k_sem_give() a
    # consumer's completion sem once per fanout edge, instead of the
    # old multi-consumer take/re-give dance — saves one sem op per
    # edge and eliminates the 64-deep limit-over-provisioning.
    fanout_entry_ids: tuple[int, ...] = ()


# ---------- parsing helpers --------------------------------------------------

_INSTANCE_RE = re.compile(r"^(?P<base>.+?)(?P<idx>\d+)$")


def _split_job_name(job: str, known: set[str] | None = None) -> tuple[str, int]:
    """Split a job_name like "mlp_control3" into ("mlp_control", 3); a name
    without a trailing instance index returns (job, 0).

    When `known` is provided, longest-prefix match against the known
    network names wins — this disambiguates models whose name ends in
    a digit (e.g. "yolov8_nano_640" → ("yolov8_nano_64", 0), not
    ("yolov8_nano_", 640))."""
    if known:
        for base in sorted(known, key=len, reverse=True):
            if job == base:
                return base, 0
            if job.startswith(base):
                rest = job[len(base):]
                if rest.isdigit():
                    return base, int(rest)
    m = _INSTANCE_RE.match(job)
    if not m:
        return job, 0
    base = m.group("base")
    idx = int(m.group("idx"))
    return base, idx


def _resolve_target(core_label: str,
                    cpu_p_kind: str, cpu_e_kind: str,
                    reg: core_registry.CoreRegistry) -> tuple[str, str, int]:
    """Resolve "CPU_P#<n>" / "CPU_E#<n>" to a registry (name, kind, hart).

    XPU-RT works in abstract machine slots (CPU_P#0, CPU_E#0). The user
    tells us which kind in the registry corresponds to each slot
    (e.g. CPU_P -> rvv, CPU_E -> scalar). We then pick the n-th core of
    that kind.
    """
    label, _, idx_str = core_label.partition("#")
    idx = int(idx_str) if idx_str else 0
    if label.upper() == "CPU_P":
        kind = cpu_p_kind
    elif label.upper() == "CPU_E":
        kind = cpu_e_kind
    else:
        raise ValueError(f"unknown machine label {core_label!r}; "
                         f"expected CPU_P#<n> or CPU_E#<n>")
    candidates = reg.by_kind.get(kind, ())
    if not candidates:
        raise ValueError(
            f"registry {reg.system!r} has no cores of kind {kind!r} "
            f"(needed by {core_label}); add one or remap with "
            f"--cpu-p-kind/--cpu-e-kind")
    if idx >= len(candidates):
        raise ValueError(
            f"{core_label} indexes core #{idx} but registry only has "
            f"{len(candidates)} cores of kind {kind!r}")
    c = candidates[idx]
    hart = c.harts[0] if c.harts else -1
    return c.name, c.kind, hart


def _resolve_targets(core_labels: str,
                     cpu_p_kind: str, cpu_e_kind: str,
                     reg: core_registry.CoreRegistry,
                     ) -> tuple[str, str, int, tuple[int, ...]]:
    """Resolve a singleton or ``+``-joined XPU-RT machine combination.

    The first target owns the dispatch and participates as shard 0.  Remaining
    targets are the helper harts reserved for the dispatch's whole execution
    window.  A ModelBlaster pool is homogeneous, so a combination that crosses
    runtime kinds is rejected instead of being flattened into a false pool.
    """
    labels = [x.strip() for x in str(core_labels).split("+") if x.strip()]
    if not labels:
        raise ValueError(f"empty hardware_target {core_labels!r}")
    resolved = [
        _resolve_target(label, cpu_p_kind, cpu_e_kind, reg)
        for label in labels
    ]
    kinds = {kind for _name, kind, _hart in resolved}
    if len(kinds) != 1:
        raise ValueError(
            f"composite target {core_labels!r} must use the same runtime kind; "
            f"resolved kinds are {sorted(kinds)}")
    harts = tuple(hart for _name, _kind, hart in resolved)
    if len(set(harts)) != len(harts):
        raise ValueError(
            f"composite target {core_labels!r} resolves the same hart twice: "
            f"{harts}")
    if len(harts) > 1 and any(hart < 0 for hart in harts):
        raise ValueError(
            f"composite target {core_labels!r} contains an unbound hart; "
            "multi-hart execution requires explicit physical harts")
    core_name, core_kind, hart = resolved[0]
    return core_name, core_kind, hart, harts


def load(schedule_path: str,
         irs_by_network: dict[str, dict],
         reg: core_registry.CoreRegistry,
         *,
         cpu_p_kind: str = "rvv",
         cpu_e_kind: str = "scalar") -> list[XpurtEntry]:
    """Parse, validate, and order an XPU-RT schedule. Returns entries
    sorted by start_time, with cross-references resolved to entry_ids."""
    with open(schedule_path) as f:
        doc = json.load(f)
    raw = doc.get("dispatches")
    if not isinstance(raw, dict) or not raw:
        raise ValueError(f"{schedule_path}: 'dispatches' missing or empty")

    # PDB-content-hash guard. The fixture (when produced by a recent
    # solver) carries `metadata.pdb_hash` and `metadata.pdb_files` —
    # the SHA256 over the profile CSVs the solver actually read. We
    # recompute the hash for the SAME paths now, before any dispatch
    # parsing, and warn (or refuse) on mismatch.
    #
    # Knob: MB_INGEST_STRICT_PDB_CHECK=1 turns the warning into a
    # hard error. Off by default to avoid breaking fixtures emitted by
    # solver versions that pre-date this metadata field — but on a
    # hash MISmatch we always emit a loud, named warning so the trap
    # is at least visible in the run log.
    meta = doc.get("metadata") if isinstance(doc.get("metadata"), dict) else {}
    fixture_hash = meta.get("pdb_hash")
    fixture_files = meta.get("pdb_files") or []
    if fixture_hash and fixture_files:
        try:
            import hashlib as _hashlib
            _h = _hashlib.sha256()
            _used: list[str] = []
            for _p in sorted(set(fixture_files)):
                if not _p:
                    continue
                try:
                    with open(_p, "rb") as _f:
                        _data = _f.read()
                except OSError:
                    continue
                _h.update(_p.encode("utf-8"))
                _h.update(b"\0")
                _h.update(len(_data).to_bytes(8, "little"))
                _h.update(_data)
                _used.append(_p)
            current_hash = _h.hexdigest()
            if current_hash != fixture_hash:
                import os as _os
                _msg = (
                    f"!! STALE-FIXTURE WARNING [{schedule_path}]\n"
                    f"   fixture pdb_hash = sha256:{fixture_hash[:16]}... "
                    f"(over {len(fixture_files)} CSV(s))\n"
                    f"   current pdb_hash = sha256:{current_hash[:16]}... "
                    f"(over {len(_used)} CSV(s) hashed)\n"
                    f"   The profile CSVs the solver used have changed on "
                    f"disk since this fixture was emitted. Predicted "
                    f"durations may not reflect what the runtime will "
                    f"actually execute.\n"
                    f"   Re-solve the workload (scripts/run_xpurt_schedule.py)\n"
                    f"   or set MB_INGEST_STRICT_PDB_CHECK=0 to acknowledge."
                )
                print(_msg)
                if _os.environ.get("MB_INGEST_STRICT_PDB_CHECK", "0") in (
                    "1", "true", "True",
                ):
                    raise RuntimeError(
                        f"{schedule_path}: PDB content hash mismatch "
                        f"(MB_INGEST_STRICT_PDB_CHECK=1)."
                    )
        except RuntimeError:
            raise
        except Exception as _e:
            # Never let the hash check itself break a load; if hashing
            # fails (e.g., permissions), print a one-line note and
            # continue with the unverified fixture.
            print(f"  (info) pdb_hash recompute skipped: {_e}")

    # Build dispatch_id index per network IR + remap from IR-space
    # dispatch_id to codegen-space dispatch table index.
    #
    # `generate_skeleton.py` filters out zero-cost IR ops (view,
    # chunk2_c1) — they're aliasing-only and produce no kernel call.
    # The dispatch table `MODEL_<UMID>_DISPATCH_FNS_<BS>[]` is built by
    # appending fns for each non-zero-cost op IN IR ORDER, so the table
    # is sized OP_COUNT == n(non-zero-cost) and indexed sequentially —
    # NOT by IR dispatch_id.
    #
    # If we passed the IR dispatch_id straight to the runtime, the
    # walker would call `MODEL_<UMID>_DISPATCH_FNS_<BS>[ir_did]` which
    # for ir_did >= n(non-zero-cost) reads past the end of the table
    # into adjacent static data and jalrs garbage. We saw exactly this
    # crash (mepc=garbage int8 weight bytes) on yolov8_nano which has 8
    # chunk2_c1 ops, so codegen produced a 204-entry table but
    # ir_dids ran 0..211.
    #
    # Fix: remap each schedule entry's IR-space dispatch_id to its
    # codegen index here. Zero-cost ops get codegen_idx=-1 — runtime
    # skips them but still posts the completion sem so dependents
    # unblock.
    _ZERO_COST_OPS = {"view", "chunk2_c1"}
    network_dispatches: dict[str, set[int]] = {}
    network_op_by_did: dict[str, dict[int, dict]] = {}
    network_remap: dict[str, dict[int, int]] = {}  # ir_did -> codegen_idx (-1 = zero-cost skip)
    for net, ir in irs_by_network.items():
        idx: dict[int, dict] = {}
        remap: dict[int, int] = {}
        codegen_idx = 0
        for op in ir.get("ops", []):
            d = op.get("dispatch_id")
            if d is None:
                continue
            idx[d] = op
            if op.get("op") in _ZERO_COST_OPS:
                remap[d] = -1
            else:
                remap[d] = codegen_idx
                codegen_idx += 1
        network_dispatches[net] = set(idx)
        network_op_by_did[net] = idx
        network_remap[net] = remap

    # ---------- IR-completion: synthesize missing IR ops ----------
    # Toggle: set MB_INGEST_SKIP_IR_COMPLETION=1 to disable the
    # synthesis pass (useful for control tests / bisecting failures).
    _skip_ir_completion = (
        os.environ.get("MB_INGEST_SKIP_IR_COMPLETION", "0") == "1")
    if _skip_ir_completion:
        print("ingest: IR-completion DISABLED via MB_INGEST_SKIP_IR_COMPLETION=1")
    if not _skip_ir_completion:
        # XPU-RT's scheduler drops IR ops whose profile-DB cost is zero
        # (relu_s8 fused into the prior BN at profile time, sigmoid_s8
        # not measured separately, etc.). Those ops still need to
        # dispatch on the harness — the generated model_<m>.c chains
        # buffers through them, so the consumer of a dropped op reads
        # stale / zero memory. Symptom before this fix: dronet output
        # stuck at zero or partial; mlp_control had only 1-2 of 7 IR
        # ops in the schedule, so the final-writeback op never fired
        # and `state.output` stayed at static zero-init.
        #
        # Fix: walk each (job_name, IR) pair. For every IR dispatch_id
        # missing from the schedule for that job, synthesize a raw
        # entry mirroring the XPU-RT schema, then thread its
        # dependencies into the topological sort. Activation ops
        # (silu/relu/elu/sigmoid/...) are pinned to the rvv_opu hart
        # since they're pure scalar FP — placing them on the gemmini
        # hart triggers a bitstream-side issue not exercised by v2.
        known_networks = set(irs_by_network)
        sched_jobs: dict[str, set[int]] = {}
        job_net_inst: dict[str, tuple[str, int]] = {}
        for k, d in raw.items():
            job = d["job_name"]
            sched_jobs.setdefault(job, set()).add(int(d["id"]))
            if job not in job_net_inst:
                net, inst = _split_job_name(job, known_networks)
                if net in known_networks:
                    job_net_inst[job] = (net, inst)

        _SCALAR_FP_OPS = {
            "silu_s8", "elu_s8", "relu_s8", "sigmoid_s8", "tanh_s8",
            "gelu_s8", "hardswish_s8", "softmax_s8",
        }
        _CPU_E_LABEL = "CPU_E#0"

        synthesized: list[tuple[str, int, str]] = []
        for job_name, scheduled_dids in list(sched_jobs.items()):
            if job_name not in job_net_inst:
                continue
            network, _instance = job_net_inst[job_name]
            ir_dids = network_dispatches.get(network, set())
            missing_dids = sorted(ir_dids - scheduled_dids)
            if not missing_dids:
                continue
            for did in missing_dids:
                op = network_op_by_did[network][did]
                op_kind = op.get("op", "")
                depends_on = op.get("depends_on", []) or []
                dep_keys: list[str] = []
                producer_max_end = 0.0
                producer_target = None
                for prod_did in depends_on:
                    prod_key = f"{job_name}_dispatch_{prod_did}"
                    if prod_key in raw:
                        dep_keys.append(prod_key)
                        pr = raw[prod_key]
                        pr_end = float(pr.get("start_time", 0.0) or 0.0) + \
                                 float(pr.get("duration", 0.0) or 0.0)
                        if pr_end > producer_max_end:
                            producer_max_end = pr_end
                        if producer_target is None:
                            producer_target = pr.get("hardware_target")
                if producer_target is None:
                    for k2, d2 in raw.items():
                        if d2.get("job_name") == job_name:
                            producer_target = d2.get("hardware_target")
                            producer_max_end = float(
                                d2.get("start_time", 0.0) or 0.0)
                            break
                if producer_target is None:
                    producer_target = "CPU_P#0"
                if op_kind in _SCALAR_FP_OPS:
                    producer_target = _CPU_E_LABEL
                new_key = f"{job_name}_dispatch_{did}"
                raw[new_key] = {
                    "id": did,
                    "ordinal": 1,
                    "total": 1,
                    "dependencies": dep_keys,
                    "hardware_target": producer_target,
                    "start_time": producer_max_end,
                    "duration": 0.0,
                    "job_name": job_name,
                    "module_name": op.get("name", f"dispatch_{did}"),
                    "_synthesized": True,
                }
                scheduled_dids.add(did)
                synthesized.append((job_name, did, new_key))

            # Thread synthesized entries into consumers' dependencies.
            synth_dids_this_job = {did for (jn, did, _k) in synthesized
                                   if jn == job_name}
            for op in irs_by_network[network].get("ops", []):
                cdid = op.get("dispatch_id")
                if cdid is None:
                    continue
                consumer_key = f"{job_name}_dispatch_{cdid}"
                if consumer_key not in raw:
                    continue
                consumer = raw[consumer_key]
                existing_deps = list(consumer.get("dependencies", []) or [])
                changed = False
                for pd in op.get("depends_on", []) or []:
                    if pd in synth_dids_this_job:
                        pk = f"{job_name}_dispatch_{pd}"
                        if pk not in existing_deps:
                            existing_deps.append(pk)
                            changed = True
                if changed:
                    consumer["dependencies"] = existing_deps

        if synthesized:
            by_job: dict[str, list[int]] = {}
            for jn, did, _k in synthesized:
                by_job.setdefault(jn, []).append(did)
            parts = ", ".join(f"{j}: {sorted(ds)}"
                              for j, ds in sorted(by_job.items()))
            print(f"ingest: synthesized {len(synthesized)} missing IR ops -> {parts}")
    # ---------- end IR-completion ----------

    # In-table order: priority topological sort, where the priority
    # key is start_time. Pure start_time-then-alphabetical sort breaks
    # down for zero-cost ops — the scheduler legitimately gives a
    # zero-cost dep and its dependent the SAME start_time (dep ends
    # the instant it starts, dependent's earliest_start = dep's end =
    # dep's start). The tie was being broken by `k` lexicographically,
    # which ranks "...dispatch_10" < "...dispatch_9" and put the
    # dependent before its dep. Kahn's-algorithm-with-heap respects
    # deps always (a dependent only becomes "runnable" after every dep
    # has been emitted) while still emitting in start_time order
    # whenever the priority queue has multiple runnable entries.
    import heapq
    from collections import defaultdict

    # Data dependencies first, on their own.
    #
    # Data deps come from the IR and are ground truth. `time_dependency` is a
    # different kind of edge: a hardware-serialisation hint that XPU-RT derived
    # from the *start times* of the dispatches it actually scheduled. Those two
    # can disagree, and the IR-completion pass above is exactly what makes them
    # disagree -- it inserts zero-cost ops the scheduler never saw, so the
    # scheduler's ordering could not have accounted for their edges.
    #
    # Observed on the 4-MLP + 2-DroNet + 1-YOLO fixture: dispatch_16 is placed
    # at 60.306 ms and data-depends on the synthesized dispatch_14, which lands
    # at 60.467 ms behind 13 &lt;- 12; meanwhile 12 carries time_dependency on 16
    # because 16 finished on CPU_P#0 the instant 12 started. That closes a
    # 12 -&gt; 16 -&gt; 14 -&gt; 13 -&gt; 12 loop and made the whole ingest fail.
    #
    # So: build the DAG from data deps, which are acyclic by construction, then
    # admit each time_dep edge only if it does not close a cycle. Dropping an
    # ordering hint costs nothing correctness-wise -- the data deps still force
    # every real ordering -- whereas honouring it makes the graph unsortable.
    adj: dict[str, list[str]] = defaultdict(list)
    indeg: dict[str, int] = {k: 0 for k in raw}
    for k, d in raw.items():
        for dep in (d.get("dependencies", []) or []):
            if dep not in raw:
                # Will be flagged later when we resolve to entry_ids;
                # don't bookkeep an edge to a non-existent node here.
                continue
            adj[dep].append(k)
            indeg[k] += 1

    def _reaches(src: str, dst: str) -> bool:
        """Is dst reachable from src along edges admitted so far?"""
        if src == dst:
            return True
        seen = {src}
        stack = [src]
        while stack:
            for nxt in adj[stack.pop()]:
                if nxt == dst:
                    return True
                if nxt not in seen:
                    seen.add(nxt)
                    stack.append(nxt)
        return False

    dropped_time_deps: list[tuple[str, str]] = []
    for k, d in sorted(raw.items()):
        time_dep_key = d.get("time_dependency")
        if not time_dep_key or time_dep_key not in raw:
            continue
        # Edge time_dep_key -> k. It closes a cycle iff k already reaches
        # time_dep_key.
        if _reaches(k, time_dep_key):
            dropped_time_deps.append((k, time_dep_key))
            continue
        adj[time_dep_key].append(k)
        indeg[k] += 1

    if dropped_time_deps:
        shown = ", ".join(f"{k} <- {t}" for k, t in dropped_time_deps[:4])
        print(f"ingest: dropped {len(dropped_time_deps)} time_dependency "
              f"edge(s) that contradicted the IR data-dependency DAG "
              f"(data deps win): {shown}"
              + (", ..." if len(dropped_time_deps) > 4 else ""))

    heap: list[tuple[float, str]] = []
    for k, n in indeg.items():
        if n == 0:
            heapq.heappush(heap, (float(raw[k].get("start_time", 0.0) or 0.0), k))
    sorted_keys: list[str] = []
    while heap:
        _, k = heapq.heappop(heap)
        sorted_keys.append(k)
        for nxt in adj[k]:
            indeg[nxt] -= 1
            if indeg[nxt] == 0:
                heapq.heappush(heap,
                               (float(raw[nxt].get("start_time", 0.0) or 0.0), nxt))
    if len(sorted_keys) != len(raw):
        # Indicates a cycle in the schedule's dep graph — an XPU-RT bug.
        unscheduled = [k for k in raw if k not in sorted_keys]
        raise ValueError(
            f"schedule dep graph has a cycle — could not topologically "
            f"order all {len(raw)} entries (only {len(sorted_keys)} placed). "
            f"Stuck entries (first 10): {unscheduled[:10]}"
        )
    key_to_entry_id = {k: i for i, k in enumerate(sorted_keys)}

    entries: list[XpurtEntry] = []
    for entry_id, key in enumerate(sorted_keys):
        d = raw[key]
        job = d["job_name"]
        network, instance = _split_job_name(job, set(irs_by_network))
        if network not in irs_by_network:
            raise ValueError(
                f"schedule entry {key!r} references unknown network {network!r}; "
                f"known: {sorted(irs_by_network)}")
        did = int(d["id"])
        if did not in network_dispatches[network]:
            raise ValueError(
                f"schedule entry {key!r}: dispatch_id={did} not in "
                f"network {network!r} (IR has {sorted(network_dispatches[network])[:8]}...)")
        op_record = network_op_by_did[network][did]

        core_name, core_kind, hart, harts = _resolve_targets(
            d["hardware_target"], cpu_p_kind, cpu_e_kind, reg)

        # PER-DISPATCH IMPLEMENTATION. With `scheduler.enable_impls` on,
        # XPU-RT emits every core-group combination once per legal
        # implementation and records the winner per dispatch, so a schedule
        # can say "this GEMM on the MAC unit, the next one on the vector
        # unit" -- on the same core. `hardware_target` cannot express that:
        # it names WHERE, and impl names WITH WHAT.
        #
        # Absent the field the answer is core_kind, which is exactly what a
        # pre-`enable_impls` schedule means, so those keep producing the
        # byte-identical table they always did.
        impl = str(d.get("impl") or core_kind)

        # Resolve deps (intra-job data deps) + time_dep (cross-job edge)
        # to in-table entry_ids. The walker's deadlock-freedom argument
        # (see modelblaster/notes/xpurt_walker_semantics.md §4.6) requires every
        # edge to point STRICTLY BACKWARD in entry_id order — i.e. only at
        # entries that have already been walked past, regardless of which
        # kind owns them. The table is start_time-sorted, so XPU-RT can
        # only legitimately produce backward edges anyway; assert it
        # explicitly here so an out-of-spec scheduler emission fails at
        # ingest instead of deadlocking the harness mid-walk.
        deps_ids: list[int] = []
        for dep_key in d.get("dependencies", []) or []:
            if dep_key not in key_to_entry_id:
                raise ValueError(
                    f"{key!r} depends on unknown entry {dep_key!r}")
            dep_id = key_to_entry_id[dep_key]
            if dep_id >= entry_id:
                raise ValueError(
                    f"{key!r} (entry_id={entry_id}) has FORWARD dep "
                    f"{dep_key!r} (entry_id={dep_id}); deps must point "
                    f"backward in start_time order. Likely a scheduler "
                    f"bug — XPU-RT should not emit forward edges.")
            deps_ids.append(dep_id)
        time_dep_id = -1
        time_dep_key = d.get("time_dependency")
        if time_dep_key:
            if time_dep_key not in key_to_entry_id:
                raise ValueError(
                    f"{key!r} time_dependency points at unknown {time_dep_key!r}")
            time_dep_id = key_to_entry_id[time_dep_key]
            if time_dep_id >= entry_id:
                raise ValueError(
                    f"{key!r} (entry_id={entry_id}) has FORWARD time_dep "
                    f"{time_dep_key!r} (entry_id={time_dep_id}); "
                    f"time_dep must point backward in start_time order.")

        codegen_did = network_remap[network][did]
        entries.append(XpurtEntry(
            entry_id=entry_id,
            schedule_key=key,
            job_name=job,
            network=network,
            instance=instance,
            # codegen-space index, matches MODEL_<UMID>_DISPATCH_FNS_<BS>[]
            # layout. -1 means "zero-cost op, runtime should skip the
            # dispatch fn call but still post the completion sem".
            dispatch_id=codegen_did,
            op=op_record["op"],
            name=op_record.get("name", f"dispatch_{did}"),
            core_name=core_name,
            core_kind=core_kind,
            impl=impl,
            hart=hart,
            harts=harts,
            start_time_ms=float(d.get("start_time", 0.0) or 0.0),
            duration_ms=float(d.get("duration", 0.0) or 0.0),
            # Dedup deps_entry_ids. Two consequences of the Phase G2d
            # producer-side fanout: (a) the consumer's take loop calls
            # k_sem_take once per dep entry, so duplicates would mean
            # multiple takes from the same producer's sem; (b) the
            # producer side dedups fanout per unique consumer. If a
            # producer ended up as both fanout[c] = c-once but the
            # consumer's deps had it twice, take/give wouldn't
            # balance and the worker deadlocks. Dedup at both ends
            # keeps the invariant 1-give = 1-take for every unique
            # (producer, consumer) edge.
            deps_entry_ids=tuple(sorted(set(deps_ids))),
            time_dep_entry_id=time_dep_id,
        ))

    # ---------- Phase G2d: producer-side fanout -----------
    # For each entry, build the set of consumers that wait on its
    # completion sem. A consumer C waits on producer P's sem when
    # either (a) P ∈ C.deps_entry_ids (data dep) or (b)
    # C.time_dep_entry_id == P (cross-job ordering). The walker uses
    # this to give the consumer's sem exactly once per fanout edge,
    # instead of having every consumer take-then-re-give. Net effect:
    # one fewer sem op per dep edge.
    fanout: list[list[int]] = [[] for _ in entries]
    for c in entries:
        for d in c.deps_entry_ids:
            if 0 <= d < len(fanout):
                fanout[d].append(c.entry_id)
        if 0 <= c.time_dep_entry_id < len(fanout):
            fanout[c.time_dep_entry_id].append(c.entry_id)
    for e in entries:
        # Sort + dedup so codegen is deterministic and a single
        # consumer connected by both a data-dep and a time-dep edge
        # only appears once in the fanout list (otherwise the walker
        # would over-signal it).
        e.fanout_entry_ids = tuple(sorted(set(fanout[e.entry_id])))

    return entries


# ---------- C-table emission --------------------------------------------------


def emit_table(entries: list[XpurtEntry], out_path: str,
               schedule_name: str) -> None:
    """Emit one .c file containing the schedule table. The header comes
    next to it as <out_path>.h."""
    h_path = out_path[:-2] + ".h" if out_path.endswith(".c") else out_path + ".h"

    upper = schedule_name.replace(".", "_").replace("-", "_").upper()

    # Build per-entry deps + fanout arrays + interned strings.
    deps_arrays: list[str] = []
    for e in entries:
        harts = ", ".join(str(h) for h in e.harts)
        deps_arrays.append(
            f"static const int sched_{e.entry_id}_harts[] = {{ {harts} }};"
        )
        if e.deps_entry_ids:
            arr = ", ".join(str(d) for d in e.deps_entry_ids)
            deps_arrays.append(
                f"static const int sched_{e.entry_id}_deps[] = {{ {arr} }};"
            )
        if e.fanout_entry_ids:
            arr = ", ".join(str(d) for d in e.fanout_entry_ids)
            deps_arrays.append(
                f"static const int sched_{e.entry_id}_fanout[] = {{ {arr} }};"
            )

    rows: list[str] = []
    for e in entries:
        n_deps = len(e.deps_entry_ids)
        deps_ref = (f"sched_{e.entry_id}_deps" if n_deps else "NULL")
        n_fanout = len(e.fanout_entry_ids)
        fanout_ref = (f"sched_{e.entry_id}_fanout" if n_fanout else "NULL")
        rows.append(
            f'    {{ .entry_id = {e.entry_id}, '
            f'.network = "{e.network}", .instance = {e.instance}, '
            f'.dispatch_id = {e.dispatch_id}, '
            f'.job_name = "{e.job_name}", '
            f'.op = "{e.op}", .name = "{e.name}", '
            f'.core_name = "{e.core_name}", .core_kind = "{e.core_kind}", '
            f'.impl = "{e.impl}", '
            f'.hart = {e.hart}, '
            f'.n_harts = {len(e.harts)}, .harts = sched_{e.entry_id}_harts, '
            f'.start_time_ms = {e.start_time_ms!r}f, '
            f'.duration_ms = {e.duration_ms!r}f, '
            f'.n_deps = {n_deps}, .deps = {deps_ref}, '
            f'.time_dep_entry_id = {e.time_dep_entry_id}, '
            f'.n_fanout = {n_fanout}, .fanout = {fanout_ref} }},'
        )

    h = f"""{HEADER}
#pragma once

#include <stddef.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* One entry per XPU-RT-scheduled dispatch, sorted by start_time.
 * The runtime walks this table; entries' .deps[] / .time_dep_entry_id
 * are in-table indices used to enforce cross-dispatch ordering. */
typedef struct {{
    int            entry_id;
    const char    *network;        /* IR network name, e.g. "mlp_control" */
    int            instance;       /* 0..K-1 across multiple instances of the same network */
    int            dispatch_id;    /* IR dispatch_id within `network` */
    const char    *job_name;       /* XPU-RT job_name, e.g. "mlp_control3" */
    const char    *op;             /* IR op kind (e.g. "linear") */
    const char    *name;           /* IR node name (e.g. "mlp.0") */
    const char    *core_name;      /* registry core name (rocket0/rvv0/...) */
    const char    *core_kind;      /* registry kind (scalar/rvv/gemmini/...) */
    const char    *impl;           /* kernel impl for THIS dispatch (rvv/ime/...);
                                    * equals core_kind unless the schedule
                                    * chose per-dispatch implementations */
    int            hart;           /* preferred hart, -1 if unbound */
    int            n_harts;        /* full reserved machine-combination width */
    const int     *harts;           /* master first, followed by helper harts */
    float          start_time_ms;  /* XPU-RT-issued start time (ms) */
    float          duration_ms;    /* XPU-RT-modeled duration (ms) */
    int            n_deps;
    const int     *deps;           /* in-table entry_ids of intra-job data deps */
    int            time_dep_entry_id; /* cross-job ordering edge, -1 if none */
    /* Producer-side fanout: entry_ids of consumers that wait on this
     * entry's completion sem (data-dep or time-dep). The walker uses
     * .n_fanout to k_sem_give() the consumer's sem exactly once per
     * consumer at producer-side, instead of the old multi-consumer
     * take/re-give pattern. */
    int            n_fanout;
    const int     *fanout;
}} xpurt_sched_entry_t;

#define {upper}_N_ENTRIES   {len(entries)}

extern const xpurt_sched_entry_t {upper}_TABLE[{upper}_N_ENTRIES];

#ifdef __cplusplus
}}
#endif
"""

    c = f"""{HEADER}
#include <stddef.h>
#include "{os.path.basename(h_path)}"

{chr(10).join(deps_arrays) if deps_arrays else "/* (no entries with deps) */"}

const xpurt_sched_entry_t {upper}_TABLE[{upper}_N_ENTRIES] = {{
{chr(10).join(rows)}
}};
"""

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(h_path, "w") as f:
        f.write(h)
    with open(out_path, "w") as f:
        f.write(c)


# ---------- CLI ---------------------------------------------------------------


def _main() -> None:
    ap = argparse.ArgumentParser(
        description="Ingest an XPU-RT schedule.json into a C dispatch table.")
    ap.add_argument("--schedule", required=True,
                    help="path to scheduled_*.json emitted by run_xpurt_schedule.py")
    ap.add_argument("--registry", required=True,
                    help="path to an modelblaster/cores/*.json")
    ap.add_argument("--ir", action="append", required=True,
                    help="<network>:<graph.json> — repeat once per network "
                         "referenced by the schedule")
    ap.add_argument("--out", required=True,
                    help="path to write the .c (companion .h is auto-derived)")
    ap.add_argument("--cpu-p-kind", default="rvv",
                    help="registry kind that CPU_P slots map to (default: rvv)")
    ap.add_argument("--cpu-e-kind", default="scalar",
                    help="registry kind that CPU_E slots map to (default: scalar)")
    ap.add_argument("--name", default=None,
                    help="schedule name (used for #define prefix); "
                         "defaults to the basename of --out without extension")
    args = ap.parse_args()

    irs: dict[str, dict] = {}
    for spec in args.ir:
        if ":" not in spec:
            raise SystemExit(f"--ir entry must be <network>:<graph.json>, got {spec!r}")
        net, path = spec.split(":", 1)
        irs[net] = json.load(open(path))

    reg = core_registry.load(args.registry)
    entries = load(args.schedule, irs, reg,
                   cpu_p_kind=args.cpu_p_kind,
                   cpu_e_kind=args.cpu_e_kind)

    schedule_name = args.name or os.path.splitext(os.path.basename(args.out))[0]
    emit_table(entries, args.out, schedule_name)
    print(f"ingested {len(entries)} entries from {args.schedule}")
    print(f"wrote {args.out}")
    print(f"wrote {args.out[:-2]}.h" if args.out.endswith(".c") else args.out + ".h")
    # Quick stats.
    by_kind: dict[str, int] = {}
    for e in entries:
        by_kind[e.core_kind] = by_kind.get(e.core_kind, 0) + 1
    print(f"by core kind: {dict(sorted(by_kind.items()))}")
    by_net: dict[str, int] = {}
    for e in entries:
        by_net[e.job_name] = by_net.get(e.job_name, 0) + 1
    print(f"by job_name: {by_net}")


if __name__ == "__main__":
    _main()
