/* @generated by modelblaster/pipeline/ingest_xpurt_schedule.py — do not edit. */
#pragma once

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* One entry per XPU-RT-scheduled dispatch, sorted by start_time.
 * The runtime walks this table; entries' .deps[] / .time_dep_entry_id
 * are in-table indices used to enforce cross-dispatch ordering. */
typedef struct {
    int            entry_id;
    const char    *network;        /* IR network name, e.g. "mlp_control" */
    int            instance;       /* 0..K-1 across multiple instances of the same network */
    int            dispatch_id;    /* IR dispatch_id within `network` */
    const char    *job_name;       /* XPU-RT job_name, e.g. "mlp_control3" */
    const char    *op;             /* IR op kind (e.g. "linear") */
    const char    *name;           /* IR node name (e.g. "mlp.0") */
    const char    *core_name;      /* registry core name (rocket0/rvv0/...) */
    const char    *core_kind;      /* registry kind (scalar/rvv/gemmini/...) */
    const char    *impl;           /* kernel impl for THIS dispatch (rvv/ime/...);
                                    * equals core_kind unless the schedule
                                    * chose per-dispatch implementations */
    int            hart;           /* preferred hart, -1 if unbound */
    int            n_harts;        /* full reserved machine-combination width */
    const int     *harts;           /* master first, followed by helper harts */
    float          start_time_ms;  /* XPU-RT-issued start time (ms) */
    float          duration_ms;    /* XPU-RT-modeled duration (ms) */
    int            n_deps;
    const int     *deps;           /* in-table entry_ids of intra-job data deps */
    int            time_dep_entry_id; /* cross-job ordering edge, -1 if none */
    /* Producer-side fanout: entry_ids of consumers that wait on this
     * entry's completion sem (data-dep or time-dep). The walker uses
     * .n_fanout to k_sem_give() the consumer's sem exactly once per
     * consumer at producer-side, instead of the old multi-consumer
     * take/re-give pattern. */
    int            n_fanout;
    const int     *fanout;
} xpurt_sched_entry_t;

#define KU040_DRONET_2BK_DEV_N_ENTRIES   20

extern const xpurt_sched_entry_t KU040_DRONET_2BK_DEV_TABLE[KU040_DRONET_2BK_DEV_N_ENTRIES];

#ifdef __cplusplus
}
#endif
