/* @generated by modelblaster/pipeline/ingest_xpurt_schedule.py — do not edit. */
#include <stddef.h>
#include "ku040_dronet_2bk_dev.h"

static const int sched_0_harts[] = { 1 };
static const int sched_0_fanout[] = { 1, 2 };
static const int sched_1_harts[] = { 0 };
static const int sched_1_deps[] = { 0 };
static const int sched_1_fanout[] = { 3 };
static const int sched_2_harts[] = { 1 };
static const int sched_2_deps[] = { 0 };
static const int sched_2_fanout[] = { 5 };
static const int sched_3_harts[] = { 1 };
static const int sched_3_deps[] = { 1 };
static const int sched_3_fanout[] = { 4 };
static const int sched_4_harts[] = { 1 };
static const int sched_4_deps[] = { 3 };
static const int sched_4_fanout[] = { 5 };
static const int sched_5_harts[] = { 0 };
static const int sched_5_deps[] = { 2, 4 };
static const int sched_5_fanout[] = { 6, 7 };
static const int sched_6_harts[] = { 0 };
static const int sched_6_deps[] = { 5 };
static const int sched_6_fanout[] = { 8 };
static const int sched_7_harts[] = { 1 };
static const int sched_7_deps[] = { 5 };
static const int sched_7_fanout[] = { 10 };
static const int sched_8_harts[] = { 1 };
static const int sched_8_deps[] = { 6 };
static const int sched_8_fanout[] = { 9 };
static const int sched_9_harts[] = { 1 };
static const int sched_9_deps[] = { 8 };
static const int sched_9_fanout[] = { 10 };
static const int sched_10_harts[] = { 0 };
static const int sched_10_deps[] = { 7, 9 };
static const int sched_10_fanout[] = { 11, 12 };
static const int sched_11_harts[] = { 0 };
static const int sched_11_deps[] = { 10 };
static const int sched_11_fanout[] = { 13 };
static const int sched_12_harts[] = { 1 };
static const int sched_12_deps[] = { 10 };
static const int sched_12_fanout[] = { 15 };
static const int sched_13_harts[] = { 1 };
static const int sched_13_deps[] = { 11 };
static const int sched_13_fanout[] = { 14 };
static const int sched_14_harts[] = { 1 };
static const int sched_14_deps[] = { 13 };
static const int sched_14_fanout[] = { 15 };
static const int sched_15_harts[] = { 0 };
static const int sched_15_deps[] = { 12, 14 };
static const int sched_15_fanout[] = { 16 };
static const int sched_16_harts[] = { 0 };
static const int sched_16_deps[] = { 15 };
static const int sched_16_fanout[] = { 17, 18 };
static const int sched_17_harts[] = { 0 };
static const int sched_17_deps[] = { 16 };
static const int sched_18_harts[] = { 0 };
static const int sched_18_deps[] = { 16 };
static const int sched_18_fanout[] = { 19 };
static const int sched_19_harts[] = { 0 };
static const int sched_19_deps[] = { 18 };

const xpurt_sched_entry_t KU040_DRONET_2BK_DEV_TABLE[KU040_DRONET_2BK_DEV_N_ENTRIES] = {
    { .entry_id = 0, .network = "dronet", .instance = 0, .dispatch_id = 0, .job_name = "dronet", .op = "conv2d_pool_s8", .name = "conv_modules.0", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_0_harts, .start_time_ms = 0.0f, .duration_ms = 0.005f, .n_deps = 0, .deps = NULL, .time_dep_entry_id = -1, .n_fanout = 2, .fanout = sched_0_fanout },
    { .entry_id = 1, .network = "dronet", .instance = 0, .dispatch_id = 1, .job_name = "dronet", .op = "batchnorm2d_s8", .name = "bn_modules.0", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_1_harts, .start_time_ms = 0.005f, .duration_ms = 0.004f, .n_deps = 1, .deps = sched_1_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_1_fanout },
    { .entry_id = 2, .network = "dronet", .instance = 0, .dispatch_id = 4, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.3", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_2_harts, .start_time_ms = 0.009f, .duration_ms = 0.035f, .n_deps = 1, .deps = sched_2_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_2_fanout },
    { .entry_id = 3, .network = "dronet", .instance = 0, .dispatch_id = 2, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.1", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_3_harts, .start_time_ms = 0.044f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_3_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_3_fanout },
    { .entry_id = 4, .network = "dronet", .instance = 0, .dispatch_id = 3, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.2", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_4_harts, .start_time_ms = 0.064f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_4_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_4_fanout },
    { .entry_id = 5, .network = "dronet", .instance = 0, .dispatch_id = 5, .job_name = "dronet", .op = "add_s8", .name = "add", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_5_harts, .start_time_ms = 0.084f, .duration_ms = 0.0025f, .n_deps = 2, .deps = sched_5_deps, .time_dep_entry_id = -1, .n_fanout = 2, .fanout = sched_5_fanout },
    { .entry_id = 6, .network = "dronet", .instance = 0, .dispatch_id = 6, .job_name = "dronet", .op = "batchnorm2d_s8", .name = "bn_modules.2", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_6_harts, .start_time_ms = 0.0865f, .duration_ms = 0.004f, .n_deps = 1, .deps = sched_6_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_6_fanout },
    { .entry_id = 7, .network = "dronet", .instance = 0, .dispatch_id = 9, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.6", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_7_harts, .start_time_ms = 0.0905f, .duration_ms = 0.035f, .n_deps = 1, .deps = sched_7_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_7_fanout },
    { .entry_id = 8, .network = "dronet", .instance = 0, .dispatch_id = 7, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.4", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_8_harts, .start_time_ms = 0.1255f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_8_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_8_fanout },
    { .entry_id = 9, .network = "dronet", .instance = 0, .dispatch_id = 8, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.5", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_9_harts, .start_time_ms = 0.1455f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_9_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_9_fanout },
    { .entry_id = 10, .network = "dronet", .instance = 0, .dispatch_id = 10, .job_name = "dronet", .op = "add_s8", .name = "add_1", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_10_harts, .start_time_ms = 0.1655f, .duration_ms = 0.0025f, .n_deps = 2, .deps = sched_10_deps, .time_dep_entry_id = -1, .n_fanout = 2, .fanout = sched_10_fanout },
    { .entry_id = 11, .network = "dronet", .instance = 0, .dispatch_id = 11, .job_name = "dronet", .op = "batchnorm2d_s8", .name = "bn_modules.4", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_11_harts, .start_time_ms = 0.168f, .duration_ms = 0.004f, .n_deps = 1, .deps = sched_11_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_11_fanout },
    { .entry_id = 12, .network = "dronet", .instance = 0, .dispatch_id = 14, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.9", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_12_harts, .start_time_ms = 0.172f, .duration_ms = 0.035f, .n_deps = 1, .deps = sched_12_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_12_fanout },
    { .entry_id = 13, .network = "dronet", .instance = 0, .dispatch_id = 12, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.7", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_13_harts, .start_time_ms = 0.207f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_13_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_13_fanout },
    { .entry_id = 14, .network = "dronet", .instance = 0, .dispatch_id = 13, .job_name = "dronet", .op = "conv2d_s8", .name = "conv_modules.8", .core_name = "gemmini_q31_0", .core_kind = "gemmini_q31", .impl = "gemmini_q31", .hart = 1, .n_harts = 1, .harts = sched_14_harts, .start_time_ms = 0.227f, .duration_ms = 0.02f, .n_deps = 1, .deps = sched_14_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_14_fanout },
    { .entry_id = 15, .network = "dronet", .instance = 0, .dispatch_id = 15, .job_name = "dronet", .op = "add_s8", .name = "add_2", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_15_harts, .start_time_ms = 0.247f, .duration_ms = 0.0025f, .n_deps = 2, .deps = sched_15_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_15_fanout },
    { .entry_id = 16, .network = "dronet", .instance = 0, .dispatch_id = 16, .job_name = "dronet", .op = "relu_s8", .name = "relu_modules.6", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_16_harts, .start_time_ms = 0.2495f, .duration_ms = 0.002f, .n_deps = 1, .deps = sched_16_deps, .time_dep_entry_id = -1, .n_fanout = 2, .fanout = sched_16_fanout },
    { .entry_id = 17, .network = "dronet", .instance = 0, .dispatch_id = 17, .job_name = "dronet", .op = "linear_s8", .name = "linear1", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_17_harts, .start_time_ms = 0.2515f, .duration_ms = 0.008f, .n_deps = 1, .deps = sched_17_deps, .time_dep_entry_id = -1, .n_fanout = 0, .fanout = NULL },
    { .entry_id = 18, .network = "dronet", .instance = 0, .dispatch_id = 18, .job_name = "dronet", .op = "linear_s8", .name = "linear2", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_18_harts, .start_time_ms = 0.2595f, .duration_ms = 0.008f, .n_deps = 1, .deps = sched_18_deps, .time_dep_entry_id = -1, .n_fanout = 1, .fanout = sched_18_fanout },
    { .entry_id = 19, .network = "dronet", .instance = 0, .dispatch_id = 19, .job_name = "dronet", .op = "sigmoid_s8", .name = "sigmoid1", .core_name = "rvv0", .core_kind = "rvv", .impl = "rvv", .hart = 0, .n_harts = 1, .harts = sched_19_harts, .start_time_ms = 0.2675f, .duration_ms = 0.005f, .n_deps = 1, .deps = sched_19_deps, .time_dep_entry_id = -1, .n_fanout = 0, .fanout = NULL },
};
