#!/usr/bin/env python3
"""Emit shared_input_main.c for the shared-input harness.

The generated main:
  1. Includes ``model.h`` (from MODEL_DIR — provides mangled type
     names, MODEL_<MID>_INPUT_SIZE / _OUTPUT_SIZE, run_model_<mid>
     prototype).
  2. Declares extern prototypes for each variant's run_model function
     (``run_model_<mid>_<tag>``). The rename headers made these visible
     in each variant's OBJECT lib.
  3. Allocates ONE shared const input reference (already in rodata via
     test_io.S; the pointer is exposed by test_io.h under the
     mangled name).
  4. Allocates N per-variant output buffers in ram0 — each
     ``MODEL_<MID>_OUTPUT_SIZE`` bytes wide. Zero-initialized so a
     variant that segfaults / doesn't write leaves distinguishable
     zeros in its own buffer, not stale data from the previous run.
  5. For each variant: reset the profile scratch, sample
     ``k_cycle_get_64()``, invoke the variant's run_model with
     ``(input, output[i], pool)``, sample again for wall cycles,
     verify against ``test_golden`` (shared), and emit the
     ``MODELBLASTER_*`` markers keyed on ``<MODEL_NAME>@<tag>`` so
     spike_runner / firesim_runner's ``--models <mid>@<tag>,...``
     parse cleanly.

Emitted output has NO renames of its own — main.c is compiled once, in
the app TU (not a variant OBJECT lib), and calls each variant's
``run_model_<mid>_<tag>`` symbol by its already-suffixed name.

Design decision: verify against the golden per variant *inside*
main.c, then still emit the raw output-block marker the parser
expects. If a variant fails verify, we emit
``MODELBLASTER_VERIFY [<mid>@<tag>] === FAIL`` and continue to the
next variant — one broken kernel doesn't abort the whole boot.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path


def _mid_from_model_h(model_h: Path) -> str:
    """Read model.h and pluck the mangled model id (e.g. 'kb_19_ReLU')
    from ``#define MODEL_<MID>_NAME "<name>"``."""
    text = model_h.read_text(errors="replace")
    m = re.search(
        r'#define\s+MODEL_([A-Z0-9_]+)_NAME\s+"([^"]+)"', text
    )
    if not m:
        raise RuntimeError(
            f"could not find MODEL_<MID>_NAME macro in {model_h}"
        )
    # <MID> is UPPER; the C source uses the mixed-case form (kb_19_ReLU
    # not KB_19_RELU) as the function-name suffix. Extract from the
    # quoted NAME string, which is exactly that mixed-case id.
    return m.group(2)


def _mid_upper(mid: str) -> str:
    return mid.upper()


def emit_main(model_dir: Path, tags: list[str], out: Path) -> None:
    mid = _mid_from_model_h(model_dir / "model.h")
    mid_u = _mid_upper(mid)
    n = len(tags)

    lines: list[str] = []
    lines.append("/* Auto-generated by gen_shared_input_main.py. DO NOT EDIT. */")
    lines.append("")
    lines.append("#include <stdio.h>")
    lines.append("#include <stdlib.h>")
    lines.append("#include <stdint.h>")
    lines.append("#include <string.h>")
    lines.append("#include <math.h>")
    lines.append("#include <zephyr/kernel.h>")
    lines.append("#include <zephyr/sys/reboot.h>")
    lines.append('#include "model.h"')
    lines.append('#include "test_io.h"')
    lines.append("")

    # Per-variant extern prototypes.
    for tag in tags:
        lines.append(
            f"extern void run_model_{mid}_{tag}("
            f"const model_{mid}_input_t *input, "
            f"model_{mid}_output_t *output, void *pool);"
        )
        lines.append(
            f"extern unsigned long model_{mid}_wall_cycles_{tag}(void);"
        )
    lines.append("")

    # Per-variant output buffers. ram0 must fit
    #     baked input (shared, rodata: input_bytes)
    #   + baked golden (shared, rodata: output_bytes)
    #   + N x output buffer (ram0: N x output_bytes)
    # The auto-ram0 sizing on the modelblaster fuse side accounts for
    # this — see harness_shared_input README for the formula.
    for tag in tags:
        lines.append(
            f"static model_{mid}_output_t out_{tag}[MODEL_{mid_u}_OUTPUT_SIZE];"
        )
    lines.append("")

    # ReLU-style tolerance envelope for the verify. Keep in sync with
    # modelblaster.validation.runner_common defaults.
    lines.append("#define _MB_ATOL 1.0e-4f")
    lines.append("#define _MB_RTOL 1.0e-4f")
    lines.append("")
    lines.append("static int verify_variant(")
    lines.append(f"    const model_{mid}_output_t *out,")
    lines.append(f"    const model_{mid}_output_t *golden,")
    lines.append("    size_t n,")
    lines.append("    const char *tag,")
    lines.append("    float *max_abs_out,")
    lines.append("    float *max_rel_out)")
    lines.append("{")
    lines.append("    float max_abs = 0.0f, max_rel = 0.0f;")
    lines.append("    for (size_t i = 0; i < n; i++) {")
    lines.append("        float a = (float)out[i];")
    lines.append("        float b = (float)golden[i];")
    lines.append("        float d = a - b;")
    lines.append("        if (d < 0.0f) d = -d;")
    lines.append("        if (d > max_abs) max_abs = d;")
    lines.append("        float denom = (b < 0.0f ? -b : b);")
    lines.append("        if (denom > 0.0f) {")
    lines.append("            float r = d / denom;")
    lines.append("            if (r > max_rel) max_rel = r;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    *max_abs_out = max_abs;")
    lines.append("    *max_rel_out = max_rel;")
    lines.append("    return (max_abs <= _MB_ATOL && max_rel <= _MB_RTOL) ? 0 : 1;")
    lines.append("}")
    lines.append("")

    # Main. Matches the single-model harness's convention: pool = NULL.
    # The generated kernels' parallel_for wrappers ignore a NULL pool
    # and fall through to the sequential path. Initializing a real pool
    # via modelblaster_pool_init(4) hangs on spike (no true SMP), and
    # for FireSim's SMP config the RL loop measures wall cycles that
    # already reflect the target's dispatch cost — the harness's own
    # pool choice would only add noise. Callers that need parallel
    # dispatch pass a pool explicitly to run_model().
    lines.append("int main(void)")
    lines.append("{")
    lines.append("    void *pool = NULL;")
    lines.append("")
    lines.append(f'    printf("modelblaster harness: model={mid} '
                 f'shared_input_variants={n} '
                 f'in=%d out=%d\\n", '
                 f'(int)MODEL_{mid_u}_INPUT_SIZE, '
                 f'(int)MODEL_{mid_u}_OUTPUT_SIZE);')
    lines.append("")
    lines.append("    float max_abs, max_rel;")
    lines.append("    int rc;")
    lines.append("    unsigned long start, wall_cycles;")
    lines.append("")

    for tag in tags:
        lines.append(f"    /* -- variant {tag} -- */")
        lines.append(
            f"    memset(out_{tag}, 0, sizeof(out_{tag}));"
        )
        lines.append(
            f"    start = (unsigned long)k_cycle_get_64();"
        )
        lines.append(
            f"    run_model_{mid}_{tag}("
            f"(const model_{mid}_input_t *)model_{mid}_test_input, "
            f"out_{tag}, pool);"
        )
        lines.append(
            f"    wall_cycles = (unsigned long)k_cycle_get_64() - start;"
        )
        lines.append(
            f"    rc = verify_variant(out_{tag}, "
            f"(const model_{mid}_output_t *)model_{mid}_test_golden, "
            f"MODEL_{mid_u}_OUTPUT_SIZE, "
            f'"{tag}", &max_abs, &max_rel);'
        )
        lines.append(
            f'    printf("=== MODELBLASTER_VERIFY [%s@{tag}] === '
            f'max_abs_err=%g max_rel_err=%g n=%d %s\\n", '
            f'MODEL_{mid_u}_NAME, (double)max_abs, (double)max_rel, '
            f'(int)MODEL_{mid_u}_OUTPUT_SIZE, '
            f'rc == 0 ? "PASS" : "FAIL");'
        )
        # Empty PROFILE block for now — the per-op mcycle plumbing lives
        # in the variant's model.c and its records_[] is file-static per
        # TU. Exposing them properly needs an extra rename entry
        # (model_<mid>_profile_records) — already in the rename list, so
        # future work can wire this up. For now the shared-input marker
        # set is: VERIFY + WALL_CYCLES.
        lines.append(
            f'    printf("=== MODELBLASTER_WALL_CYCLES [%s@{tag}] === %lu\\n", '
            f'MODEL_{mid_u}_NAME, wall_cycles);'
        )
        lines.append("")

    lines.append('    printf("modelblaster harness: shared_input all variants done\\n");')
    lines.append("    (void)pool;")
    lines.append("")
    lines.append("    /* Trigger Zephyr shutdown so HTIF emits the terminator")
    lines.append("     * marker (spike_runner / firesim_runner tail uartlog for")
    lines.append("     * \"Simulation complete\"; without this the runner blocks")
    lines.append("     * on the outer timeout even though all WALL_CYCLES markers")
    lines.append("     * have already been emitted). Mirrors harness/src/main.c's")
    lines.append("     * same-shape exit block. */")
    lines.append("#ifdef CONFIG_ARCH_POSIX")
    lines.append("    exit(0);")
    lines.append("#else")
    lines.append("    sys_reboot(SYS_REBOOT_COLD);")
    lines.append("#endif")
    lines.append("    return 0;")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--model-dir", required=True, type=Path)
    ap.add_argument("--tags", required=True,
                    help="Comma-separated variant tags parallel to VARIANT_SOURCES.")
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()
    tags = [t.strip() for t in args.tags.split(",") if t.strip()]
    if not tags:
        raise SystemExit("--tags is empty")
    emit_main(args.model_dir, tags, args.out)


if __name__ == "__main__":
    main()
