set(kconfig_env_dirs)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_ESPRESSIF_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/hal/espressif)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_ST_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/hal/st)
list(APPEND kconfig_env_dirs ZEPHYR_ACPICA_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/lib/acpica)
list(APPEND kconfig_env_dirs ZEPHYR_CMSIS_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/hal/cmsis)
list(APPEND kconfig_env_dirs ZEPHYR_CMSIS_DSP_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/lib/cmsis-dsp)
list(APPEND kconfig_env_dirs ZEPHYR_CMSIS_NN_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/lib/cmsis-nn)
list(APPEND kconfig_env_dirs ZEPHYR_FATFS_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/fs/fatfs)
list(APPEND kconfig_env_dirs ZEPHYR_LITTLEFS_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/fs/littlefs)
list(APPEND kconfig_env_dirs ZEPHYR_LVGL_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/lib/gui/lvgl)
list(APPEND kconfig_env_dirs ZEPHYR_MBEDTLS_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/crypto/mbedtls)
list(APPEND kconfig_env_dirs ZEPHYR_MCUBOOT_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/bootloader/mcuboot)
list(APPEND kconfig_env_dirs ZEPHYR_MIPI_SYS_T_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/debug/mipi-sys-t)
list(APPEND kconfig_env_dirs ZEPHYR_OPEN_AMP_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/lib/open-amp)
list(APPEND kconfig_env_dirs ZEPHYR_OPENTHREAD_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/lib/openthread)
list(APPEND kconfig_env_dirs ZEPHYR_PERCEPIO_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/debug/percepio)
list(APPEND kconfig_env_dirs ZEPHYR_PICOLIBC_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/lib/picolibc)
list(APPEND kconfig_env_dirs ZEPHYR_TINYCRYPT_MODULE_DIR=/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/zephyr_ws/modules/crypto/tinycrypt)
