#!/usr/bin/env bash
# @generated by experiments/workload_gen/mk_scaled_variants.py
# dronet scaled variant s2 (small): MODELBLASTER_DRONET_INPUT=64
#
# MB_DRIFT_ATOL=2 matches the arm-B convention: without it generate_kernels'
# verify gate rejects gemmini_tiled_conv and silently falls back to the
# ~3.45x slower software im2col.
set -euo pipefail
export MB_DRIFT_ATOL="${MB_DRIFT_ATOL:-2}"
MODEL_NAME=dronet_s2
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export MODEL_NAME REPO_ROOT
source "${REPO_ROOT}/examples/_run_lib.sh"
