#!/usr/bin/env bash
# Phase 3 — 3-way frequency sweep.
# Runs each of the 5 fixture variants generated by gen_3way_matrix.sh through
# the xpurt_demo end-to-end (build + FireSim + verify). All captures go through
# firesim-queue and serialize.
#
# After each rep the queue's uartlog is copied into the per-config results dir
# so per-instance cycles can be parsed offline.
#
# Each config takes ~30-60 min wall depending on dispatch count
# (baseline=270 → ~30 min; camera-60hz=1682 → ~90 min). Total ~5 hr.
#
# Usage:
#   bash scripts/run_3way_sweep.sh [config...]
# Default: all 5 configs (baseline conservative camera-30hz camera-60hz imu-only-hi).

cd "$(dirname "$0")/.."

# Source the env script WITHOUT set -e: it triggers a non-zero return on
# checks that don't matter for our case, which would abort under pipefail.
source scripts/setup_benchmark_env.sh >/dev/null 2>&1 || true
export FIRESIM_QUEUE=1
export MODELS="yolov8_nano,dronet,mlp_control"
export QUANTS="int8,int8,fp32"
export BACKENDS="gemmini,rvv_opu"
export REGISTRY="$PWD/cores/chipyard_gemmini_opu_hetero.json"
export CPU_P_KIND="gemmini"
export CPU_E_KIND="rvv_opu"
export RUNNER="firesim"
export FIRESIM_QUEUE_TIMEOUT="3600"
# Record per-dispatch start/end cycles into the in-binary xpurt_trace[]
# array during execution; the trace is dumped as ONE block at the end of
# the run via printk. No per-dispatch printk overhead during measurement.
export XPURT_TRACE=1

if [[ $# -gt 0 ]]; then
  CONFIGS=("$@")
else
  CONFIGS=(baseline conservative camera-30hz camera-60hz imu-only-hi)
fi
LOG=/tmp/mb-matrix/3way_sweep.log
mkdir -p "$(dirname "$LOG")"
: > "$LOG"

for cfg in "${CONFIGS[@]}"; do
  FX="$PWD/schedule_fixtures/3way_${cfg}.json"
  if [[ ! -f "$FX" ]]; then
    echo "MISSING fixture: $FX — skip $cfg" | tee -a "$LOG"
    continue
  fi
  RESULTS_DIR="$PWD/benchmarks/results/A/3way_${cfg}/$(date +%Y%m%dT%H%M%SZ)"
  mkdir -p "$RESULTS_DIR"

  export SCHEDULE_JSON="$FX"
  # SCHED_NAME becomes a C symbol prefix in generated main.c — must start
  # with a letter, no dashes. Map e.g. "camera-30hz" -> "sweep_camera_30hz".
  safe_name="sweep_${cfg//-/_}"
  export SCHED_NAME="$safe_name"

  echo "=== 3way sweep [$cfg / $safe_name] start $(date +%T) -> $RESULTS_DIR ===" | tee -a "$LOG"
  # Capture run.sh stdout into the per-config results dir so we can later
  # see per-instance bit-exact + per-model verify summaries from the host
  # post-processor (not just FPGA UART). The | tee also keeps the central
  # log so we can scan timestamps across configs.
  uv run bash examples/xpurt_demo/run.sh 2>&1 | tee "$RESULTS_DIR/run_stdout.log" >> "$LOG"
  rc=${PIPESTATUS[0]}
  echo "  rc=$rc at $(date +%T)" | tee -a "$LOG"

  # Identify THIS run's uartlog by extracting the firesim-queue job id from
  # our stdout (firesim_runner.py emits "job_id=NN" via firesim-queue).
  # Falls back to mtime-based find if the marker is missing (e.g. when
  # FIRESIM_QUEUE=0).
  JOB_ID=$(grep -oE 'job_id=([0-9]+)' "$RESULTS_DIR/run_stdout.log" | head -1 | cut -d= -f2)
  Q_UART=""
  if [[ -n "$JOB_ID" ]]; then
    Q_UART=$(find /scratch2/agustin/chipyard/sims/firesim/deploy/results-workload \
                  -path "*-q${JOB_ID}/*" -name 'uartlog' 2>/dev/null | head -1)
  fi
  if [[ -z "$Q_UART" ]]; then
    Q_UART=$(find /scratch2/agustin/chipyard/sims/firesim/deploy/results-workload \
                  -name 'uartlog' -newer "$RESULTS_DIR" 2>/dev/null | head -1)
  fi
  if [[ -n "$Q_UART" ]]; then
    cp "$Q_UART" "$RESULTS_DIR/uartlog"
    echo "  uartlog (job_id=${JOB_ID:-?}) -> $RESULTS_DIR/uartlog" | tee -a "$LOG"

    # Extract the per-dispatch trace block (emitted ONCE at end of run, after
    # all dispatches complete — no measurement overhead). Drop into the same
    # CSV format arm_a_curated produces so plot_gantt + postmortem just work.
    python3 - "$RESULTS_DIR/uartlog" "$RESULTS_DIR/xpurt_trace.csv" <<'PY'
import sys
src, dst = sys.argv[1:3]
text = open(src).read()
B = "=== MODELBLASTER_XPURT_TRACE_BEGIN ==="
E = "=== MODELBLASTER_XPURT_TRACE_END ==="
if B in text and E in text:
    body = text[text.index(B)+len(B):text.index(E, text.index(B))].strip()
    with open(dst, "w") as f:
        f.write(body + "\n")
    print(f"  trace -> {dst} ({body.count(chr(10))+1} rows)")
else:
    print("  WARN: trace block missing (XPURT_TRACE=0 in build?)")
PY
  else
    echo "  WARN: no uartlog found for job_id=${JOB_ID:-?}" | tee -a "$LOG"
  fi
done

echo "=== 3way sweep done $(date +%T) ===" | tee -a "$LOG"
