CONFIG_MAIN_STACK_SIZE=524288
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_FPU=y
CONFIG_RISCV_ISA_EXT_V=y
CONFIG_RISCV_ISA_EXT_ZFH=y
CONFIG_RISCV_ISA_EXT_ZVFH=y
CONFIG_RISCV_ISA_EXT_V_LAZY=n
CONFIG_RISCV_V_KERNEL_ONLY=y
