"""yolov8_nano scaled variant s7 (huge): MODELBLASTER_YOLOV8N_INPUT=320.

@generated by experiments/workload_gen/mk_scaled_variants.py -- do not edit.

Sets the scale BEFORE importing the backing module, which reads the env var
at import / model-build time. Non-default rungs keep their seeded random
init (the trained checkpoint only fits the default geometry), so this is a
valid latency/scheduling target and NOT an accuracy result.
"""
import os

os.environ["MODELBLASTER_YOLOV8N_INPUT"] = "320"

from . import yolov8_nano as _base  # noqa: E402


def get_model(seed: int = 0):
    return _base.get_model(seed)


def get_sample_input(seed: int = 1):
    return _base.get_sample_input(seed)


__all__ = ["get_model", "get_sample_input"]
